// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compact_formats.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// CompactBlock is a packaging of ONLY the data from a block that's needed to:
//   1. Detect a payment to your shielded Sapling address
//   2. Detect a spend of your shielded Sapling notes
//   3. Update your witnesses to generate new Sapling spend proofs.
type CompactBlock struct {
	ProtoVersion         uint32       `protobuf:"varint,1,opt,name=protoVersion,proto3" json:"protoVersion,omitempty"`
	Height               uint64       `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Hash                 []byte       `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Time                 uint32       `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Header               []byte       `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	Vtx                  []*CompactTx `protobuf:"bytes,6,rep,name=vtx,proto3" json:"vtx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CompactBlock) Reset()         { *m = CompactBlock{} }
func (m *CompactBlock) String() string { return proto.CompactTextString(m) }
func (*CompactBlock) ProtoMessage()    {}
func (*CompactBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_compact_formats_9dd2f8e478a3b8fc, []int{0}
}
func (m *CompactBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompactBlock.Unmarshal(m, b)
}
func (m *CompactBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompactBlock.Marshal(b, m, deterministic)
}
func (dst *CompactBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompactBlock.Merge(dst, src)
}
func (m *CompactBlock) XXX_Size() int {
	return xxx_messageInfo_CompactBlock.Size(m)
}
func (m *CompactBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_CompactBlock.DiscardUnknown(m)
}

var xxx_messageInfo_CompactBlock proto.InternalMessageInfo

func (m *CompactBlock) GetProtoVersion() uint32 {
	if m != nil {
		return m.ProtoVersion
	}
	return 0
}

func (m *CompactBlock) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *CompactBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *CompactBlock) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *CompactBlock) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CompactBlock) GetVtx() []*CompactTx {
	if m != nil {
		return m.Vtx
	}
	return nil
}

type CompactTx struct {
	// Index and hash will allow the receiver to call out to chain
	// explorers or other data structures to retrieve more information
	// about this transaction.
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Hash  []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// The transaction fee: present if server can provide. In the case of a
	// stateless server and a transaction with transparent inputs, this will be
	// unset because the calculation requires reference to prior transactions.
	// in a pure-Sapling context, the fee will be calculable as:
	//    valueBalance + (sum(vPubNew) - sum(vPubOld) - sum(tOut))
	Fee                  uint32           `protobuf:"varint,3,opt,name=fee,proto3" json:"fee,omitempty"`
	Spends               []*CompactSpend  `protobuf:"bytes,4,rep,name=spends,proto3" json:"spends,omitempty"`
	Outputs              []*CompactOutput `protobuf:"bytes,5,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CompactTx) Reset()         { *m = CompactTx{} }
func (m *CompactTx) String() string { return proto.CompactTextString(m) }
func (*CompactTx) ProtoMessage()    {}
func (*CompactTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_compact_formats_9dd2f8e478a3b8fc, []int{1}
}
func (m *CompactTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompactTx.Unmarshal(m, b)
}
func (m *CompactTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompactTx.Marshal(b, m, deterministic)
}
func (dst *CompactTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompactTx.Merge(dst, src)
}
func (m *CompactTx) XXX_Size() int {
	return xxx_messageInfo_CompactTx.Size(m)
}
func (m *CompactTx) XXX_DiscardUnknown() {
	xxx_messageInfo_CompactTx.DiscardUnknown(m)
}

var xxx_messageInfo_CompactTx proto.InternalMessageInfo

func (m *CompactTx) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *CompactTx) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *CompactTx) GetFee() uint32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *CompactTx) GetSpends() []*CompactSpend {
	if m != nil {
		return m.Spends
	}
	return nil
}

func (m *CompactTx) GetOutputs() []*CompactOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type CompactSpend struct {
	Nf                   []byte   `protobuf:"bytes,1,opt,name=nf,proto3" json:"nf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompactSpend) Reset()         { *m = CompactSpend{} }
func (m *CompactSpend) String() string { return proto.CompactTextString(m) }
func (*CompactSpend) ProtoMessage()    {}
func (*CompactSpend) Descriptor() ([]byte, []int) {
	return fileDescriptor_compact_formats_9dd2f8e478a3b8fc, []int{2}
}
func (m *CompactSpend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompactSpend.Unmarshal(m, b)
}
func (m *CompactSpend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompactSpend.Marshal(b, m, deterministic)
}
func (dst *CompactSpend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompactSpend.Merge(dst, src)
}
func (m *CompactSpend) XXX_Size() int {
	return xxx_messageInfo_CompactSpend.Size(m)
}
func (m *CompactSpend) XXX_DiscardUnknown() {
	xxx_messageInfo_CompactSpend.DiscardUnknown(m)
}

var xxx_messageInfo_CompactSpend proto.InternalMessageInfo

func (m *CompactSpend) GetNf() []byte {
	if m != nil {
		return m.Nf
	}
	return nil
}

type CompactOutput struct {
	Cmu                  []byte   `protobuf:"bytes,1,opt,name=cmu,proto3" json:"cmu,omitempty"`
	Epk                  []byte   `protobuf:"bytes,2,opt,name=epk,proto3" json:"epk,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompactOutput) Reset()         { *m = CompactOutput{} }
func (m *CompactOutput) String() string { return proto.CompactTextString(m) }
func (*CompactOutput) ProtoMessage()    {}
func (*CompactOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_compact_formats_9dd2f8e478a3b8fc, []int{3}
}
func (m *CompactOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompactOutput.Unmarshal(m, b)
}
func (m *CompactOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompactOutput.Marshal(b, m, deterministic)
}
func (dst *CompactOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompactOutput.Merge(dst, src)
}
func (m *CompactOutput) XXX_Size() int {
	return xxx_messageInfo_CompactOutput.Size(m)
}
func (m *CompactOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CompactOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CompactOutput proto.InternalMessageInfo

func (m *CompactOutput) GetCmu() []byte {
	if m != nil {
		return m.Cmu
	}
	return nil
}

func (m *CompactOutput) GetEpk() []byte {
	if m != nil {
		return m.Epk
	}
	return nil
}

func (m *CompactOutput) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func init() {
	proto.RegisterType((*CompactBlock)(nil), "rpc.CompactBlock")
	proto.RegisterType((*CompactTx)(nil), "rpc.CompactTx")
	proto.RegisterType((*CompactSpend)(nil), "rpc.CompactSpend")
	proto.RegisterType((*CompactOutput)(nil), "rpc.CompactOutput")
}

func init() {
	proto.RegisterFile("compact_formats.proto", fileDescriptor_compact_formats_9dd2f8e478a3b8fc)
}

var fileDescriptor_compact_formats_9dd2f8e478a3b8fc = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0x4b, 0x4e, 0xc3, 0x30,
	0x10, 0x55, 0x3e, 0x0d, 0x62, 0x48, 0x2b, 0x18, 0x01, 0xf2, 0xaa, 0x8a, 0xb2, 0x0a, 0x12, 0xea,
	0x02, 0x6e, 0x00, 0x07, 0x40, 0x72, 0x11, 0x5b, 0x14, 0x5c, 0x87, 0x44, 0x25, 0xb1, 0x65, 0xbb,
	0x28, 0xc7, 0xe1, 0x00, 0x1c, 0x12, 0x79, 0x6a, 0xa2, 0x74, 0xf7, 0xe6, 0xbd, 0x37, 0x33, 0xcf,
	0x63, 0xb8, 0x11, 0xaa, 0xd7, 0xb5, 0x70, 0xef, 0x8d, 0x32, 0x7d, 0xed, 0xec, 0x46, 0x1b, 0xe5,
	0x14, 0x26, 0x46, 0x8b, 0xf2, 0x37, 0x82, 0xfc, 0xf9, 0x28, 0x3f, 0x7d, 0x29, 0xb1, 0xc7, 0x12,
	0x72, 0x92, 0xdf, 0xa4, 0xb1, 0x9d, 0x1a, 0x58, 0x54, 0x44, 0xd5, 0x92, 0x9f, 0x70, 0x78, 0x0b,
	0x59, 0x2b, 0xbb, 0xcf, 0xd6, 0xb1, 0xb8, 0x88, 0xaa, 0x94, 0x87, 0x0a, 0x11, 0xd2, 0xb6, 0xb6,
	0x2d, 0x4b, 0x8a, 0xa8, 0xca, 0x39, 0x61, 0xcf, 0xb9, 0xae, 0x97, 0x2c, 0xa5, 0x39, 0x84, 0x8f,
	0xfd, 0xf5, 0x4e, 0x1a, 0xb6, 0x20, 0x67, 0xa8, 0xb0, 0x80, 0xe4, 0xdb, 0x8d, 0x2c, 0x2b, 0x92,
	0xea, 0xe2, 0x61, 0xb5, 0x31, 0x5a, 0x6c, 0x42, 0xb6, 0xd7, 0x91, 0x7b, 0xa9, 0xfc, 0x89, 0xe0,
	0x7c, 0xa2, 0xf0, 0x1a, 0x16, 0xdd, 0xb0, 0x93, 0x23, 0x85, 0x4c, 0xf9, 0xb1, 0x98, 0x52, 0xc4,
	0xb3, 0x14, 0x97, 0x90, 0x34, 0x52, 0x52, 0xb0, 0x25, 0xf7, 0x10, 0xef, 0x20, 0xb3, 0x5a, 0x0e,
	0x3b, 0xcb, 0x52, 0x5a, 0x77, 0x35, 0x5f, 0xb7, 0xf5, 0x0a, 0x0f, 0x06, 0xbc, 0x87, 0x33, 0x75,
	0x70, 0xfa, 0xe0, 0x2c, 0x5b, 0x90, 0x17, 0xe7, 0xde, 0x17, 0x92, 0xf8, 0xbf, 0xa5, 0x5c, 0x4f,
	0x07, 0xa5, 0x29, 0xb8, 0x82, 0x78, 0x68, 0x28, 0x61, 0xce, 0xe3, 0xa1, 0x29, 0xb7, 0xb0, 0x3c,
	0xe9, 0xf4, 0xd9, 0x44, 0x7f, 0x08, 0x0e, 0x0f, 0x3d, 0x23, 0xf5, 0x3e, 0x3c, 0xc0, 0x43, 0x5c,
	0x03, 0x88, 0x4e, 0xb7, 0xd2, 0x38, 0x39, 0xba, 0x70, 0xdf, 0x19, 0xf3, 0x91, 0xd1, 0xff, 0x3c,
	0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x23, 0xf6, 0xee, 0xeb, 0x01, 0x00, 0x00,
}
