// Copyright (c) 2019-2020 The Zcash developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://www.opensource.org/licenses/mit-license.php .

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: darkside.proto

package walletrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DarksideMetaState struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	SaplingActivation              int32                  `protobuf:"varint,1,opt,name=saplingActivation,proto3" json:"saplingActivation,omitempty"`
	BranchID                       string                 `protobuf:"bytes,2,opt,name=branchID,proto3" json:"branchID,omitempty"`
	ChainName                      string                 `protobuf:"bytes,3,opt,name=chainName,proto3" json:"chainName,omitempty"`
	StartSaplingCommitmentTreeSize uint32                 `protobuf:"varint,4,opt,name=startSaplingCommitmentTreeSize,proto3" json:"startSaplingCommitmentTreeSize,omitempty"`
	StartOrchardCommitmentTreeSize uint32                 `protobuf:"varint,5,opt,name=startOrchardCommitmentTreeSize,proto3" json:"startOrchardCommitmentTreeSize,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *DarksideMetaState) Reset() {
	*x = DarksideMetaState{}
	mi := &file_darkside_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DarksideMetaState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DarksideMetaState) ProtoMessage() {}

func (x *DarksideMetaState) ProtoReflect() protoreflect.Message {
	mi := &file_darkside_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DarksideMetaState.ProtoReflect.Descriptor instead.
func (*DarksideMetaState) Descriptor() ([]byte, []int) {
	return file_darkside_proto_rawDescGZIP(), []int{0}
}

func (x *DarksideMetaState) GetSaplingActivation() int32 {
	if x != nil {
		return x.SaplingActivation
	}
	return 0
}

func (x *DarksideMetaState) GetBranchID() string {
	if x != nil {
		return x.BranchID
	}
	return ""
}

func (x *DarksideMetaState) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *DarksideMetaState) GetStartSaplingCommitmentTreeSize() uint32 {
	if x != nil {
		return x.StartSaplingCommitmentTreeSize
	}
	return 0
}

func (x *DarksideMetaState) GetStartOrchardCommitmentTreeSize() uint32 {
	if x != nil {
		return x.StartOrchardCommitmentTreeSize
	}
	return 0
}

// A block is a hex-encoded string.
type DarksideBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         string                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DarksideBlock) Reset() {
	*x = DarksideBlock{}
	mi := &file_darkside_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DarksideBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DarksideBlock) ProtoMessage() {}

func (x *DarksideBlock) ProtoReflect() protoreflect.Message {
	mi := &file_darkside_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DarksideBlock.ProtoReflect.Descriptor instead.
func (*DarksideBlock) Descriptor() ([]byte, []int) {
	return file_darkside_proto_rawDescGZIP(), []int{1}
}

func (x *DarksideBlock) GetBlock() string {
	if x != nil {
		return x.Block
	}
	return ""
}

// DarksideBlocksURL is typically something like:
// https://raw.githubusercontent.com/zcash-hackworks/darksidewalletd-test-data/master/basic-reorg/before-reorg.txt
type DarksideBlocksURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DarksideBlocksURL) Reset() {
	*x = DarksideBlocksURL{}
	mi := &file_darkside_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DarksideBlocksURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DarksideBlocksURL) ProtoMessage() {}

func (x *DarksideBlocksURL) ProtoReflect() protoreflect.Message {
	mi := &file_darkside_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DarksideBlocksURL.ProtoReflect.Descriptor instead.
func (*DarksideBlocksURL) Descriptor() ([]byte, []int) {
	return file_darkside_proto_rawDescGZIP(), []int{2}
}

func (x *DarksideBlocksURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// DarksideTransactionsURL refers to an HTTP source that contains a list
// of hex-encoded transactions, one per line, that are to be associated
// with the given height (fake-mined into the block at that height)
type DarksideTransactionsURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DarksideTransactionsURL) Reset() {
	*x = DarksideTransactionsURL{}
	mi := &file_darkside_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DarksideTransactionsURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DarksideTransactionsURL) ProtoMessage() {}

func (x *DarksideTransactionsURL) ProtoReflect() protoreflect.Message {
	mi := &file_darkside_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DarksideTransactionsURL.ProtoReflect.Descriptor instead.
func (*DarksideTransactionsURL) Descriptor() ([]byte, []int) {
	return file_darkside_proto_rawDescGZIP(), []int{3}
}

func (x *DarksideTransactionsURL) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DarksideTransactionsURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DarksideHeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DarksideHeight) Reset() {
	*x = DarksideHeight{}
	mi := &file_darkside_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DarksideHeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DarksideHeight) ProtoMessage() {}

func (x *DarksideHeight) ProtoReflect() protoreflect.Message {
	mi := &file_darkside_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DarksideHeight.ProtoReflect.Descriptor instead.
func (*DarksideHeight) Descriptor() ([]byte, []int) {
	return file_darkside_proto_rawDescGZIP(), []int{4}
}

func (x *DarksideHeight) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type DarksideEmptyBlocks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Nonce         int32                  `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DarksideEmptyBlocks) Reset() {
	*x = DarksideEmptyBlocks{}
	mi := &file_darkside_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DarksideEmptyBlocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DarksideEmptyBlocks) ProtoMessage() {}

func (x *DarksideEmptyBlocks) ProtoReflect() protoreflect.Message {
	mi := &file_darkside_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DarksideEmptyBlocks.ProtoReflect.Descriptor instead.
func (*DarksideEmptyBlocks) Descriptor() ([]byte, []int) {
	return file_darkside_proto_rawDescGZIP(), []int{5}
}

func (x *DarksideEmptyBlocks) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DarksideEmptyBlocks) GetNonce() int32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *DarksideEmptyBlocks) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DarksideSubtreeRoots struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ShieldedProtocol ShieldedProtocol       `protobuf:"varint,1,opt,name=shieldedProtocol,proto3,enum=cash.z.wallet.sdk.rpc.ShieldedProtocol" json:"shieldedProtocol,omitempty"`
	StartIndex       uint32                 `protobuf:"varint,2,opt,name=startIndex,proto3" json:"startIndex,omitempty"`
	SubtreeRoots     []*SubtreeRoot         `protobuf:"bytes,3,rep,name=subtreeRoots,proto3" json:"subtreeRoots,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DarksideSubtreeRoots) Reset() {
	*x = DarksideSubtreeRoots{}
	mi := &file_darkside_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DarksideSubtreeRoots) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DarksideSubtreeRoots) ProtoMessage() {}

func (x *DarksideSubtreeRoots) ProtoReflect() protoreflect.Message {
	mi := &file_darkside_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DarksideSubtreeRoots.ProtoReflect.Descriptor instead.
func (*DarksideSubtreeRoots) Descriptor() ([]byte, []int) {
	return file_darkside_proto_rawDescGZIP(), []int{6}
}

func (x *DarksideSubtreeRoots) GetShieldedProtocol() ShieldedProtocol {
	if x != nil {
		return x.ShieldedProtocol
	}
	return ShieldedProtocol_sapling
}

func (x *DarksideSubtreeRoots) GetStartIndex() uint32 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *DarksideSubtreeRoots) GetSubtreeRoots() []*SubtreeRoot {
	if x != nil {
		return x.SubtreeRoots
	}
	return nil
}

var File_darkside_proto protoreflect.FileDescriptor

const file_darkside_proto_rawDesc = "" +
	"\n" +
	"\x0edarkside.proto\x12\x15cash.z.wallet.sdk.rpc\x1a\rservice.proto\"\x8b\x02\n" +
	"\x11DarksideMetaState\x12,\n" +
	"\x11saplingActivation\x18\x01 \x01(\x05R\x11saplingActivation\x12\x1a\n" +
	"\bbranchID\x18\x02 \x01(\tR\bbranchID\x12\x1c\n" +
	"\tchainName\x18\x03 \x01(\tR\tchainName\x12F\n" +
	"\x1estartSaplingCommitmentTreeSize\x18\x04 \x01(\rR\x1estartSaplingCommitmentTreeSize\x12F\n" +
	"\x1estartOrchardCommitmentTreeSize\x18\x05 \x01(\rR\x1estartOrchardCommitmentTreeSize\"%\n" +
	"\rDarksideBlock\x12\x14\n" +
	"\x05block\x18\x01 \x01(\tR\x05block\"%\n" +
	"\x11DarksideBlocksURL\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"C\n" +
	"\x17DarksideTransactionsURL\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"(\n" +
	"\x0eDarksideHeight\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\"Y\n" +
	"\x13DarksideEmptyBlocks\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x05R\x05nonce\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xd3\x01\n" +
	"\x14DarksideSubtreeRoots\x12S\n" +
	"\x10shieldedProtocol\x18\x01 \x01(\x0e2'.cash.z.wallet.sdk.rpc.ShieldedProtocolR\x10shieldedProtocol\x12\x1e\n" +
	"\n" +
	"startIndex\x18\x02 \x01(\rR\n" +
	"startIndex\x12F\n" +
	"\fsubtreeRoots\x18\x03 \x03(\v2\".cash.z.wallet.sdk.rpc.SubtreeRootR\fsubtreeRoots2\xaa\v\n" +
	"\x10DarksideStreamer\x12Q\n" +
	"\x05Reset\x12(.cash.z.wallet.sdk.rpc.DarksideMetaState\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00\x12[\n" +
	"\x11StageBlocksStream\x12$.cash.z.wallet.sdk.rpc.DarksideBlock\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00(\x01\x12W\n" +
	"\vStageBlocks\x12(.cash.z.wallet.sdk.rpc.DarksideBlocksURL\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00\x12_\n" +
	"\x11StageBlocksCreate\x12*.cash.z.wallet.sdk.rpc.DarksideEmptyBlocks\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00\x12b\n" +
	"\x17StageTransactionsStream\x12%.cash.z.wallet.sdk.rpc.RawTransaction\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00(\x01\x12c\n" +
	"\x11StageTransactions\x12..cash.z.wallet.sdk.rpc.DarksideTransactionsURL\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00\x12T\n" +
	"\vApplyStaged\x12%.cash.z.wallet.sdk.rpc.DarksideHeight\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00\x12b\n" +
	"\x17GetIncomingTransactions\x12\x1c.cash.z.wallet.sdk.rpc.Empty\x1a%.cash.z.wallet.sdk.rpc.RawTransaction\"\x000\x01\x12Y\n" +
	"\x19ClearIncomingTransactions\x12\x1c.cash.z.wallet.sdk.rpc.Empty\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00\x12]\n" +
	"\x0eAddAddressUtxo\x12+.cash.z.wallet.sdk.rpc.GetAddressUtxosReply\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00\x12P\n" +
	"\x10ClearAddressUtxo\x12\x1c.cash.z.wallet.sdk.rpc.Empty\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00\x12P\n" +
	"\fAddTreeState\x12 .cash.z.wallet.sdk.rpc.TreeState\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00\x12Q\n" +
	"\x0fRemoveTreeState\x12\x1e.cash.z.wallet.sdk.rpc.BlockID\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00\x12R\n" +
	"\x12ClearAllTreeStates\x12\x1c.cash.z.wallet.sdk.rpc.Empty\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00\x12^\n" +
	"\x0fSetSubtreeRoots\x12+.cash.z.wallet.sdk.rpc.DarksideSubtreeRoots\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00\x12D\n" +
	"\x04Stop\x12\x1c.cash.z.wallet.sdk.rpc.Empty\x1a\x1c.cash.z.wallet.sdk.rpc.Empty\"\x00B\x1bZ\x16lightwalletd/walletrpc\xba\x02\x00b\x06proto3"

var (
	file_darkside_proto_rawDescOnce sync.Once
	file_darkside_proto_rawDescData []byte
)

func file_darkside_proto_rawDescGZIP() []byte {
	file_darkside_proto_rawDescOnce.Do(func() {
		file_darkside_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_darkside_proto_rawDesc), len(file_darkside_proto_rawDesc)))
	})
	return file_darkside_proto_rawDescData
}

var file_darkside_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_darkside_proto_goTypes = []any{
	(*DarksideMetaState)(nil),       // 0: cash.z.wallet.sdk.rpc.DarksideMetaState
	(*DarksideBlock)(nil),           // 1: cash.z.wallet.sdk.rpc.DarksideBlock
	(*DarksideBlocksURL)(nil),       // 2: cash.z.wallet.sdk.rpc.DarksideBlocksURL
	(*DarksideTransactionsURL)(nil), // 3: cash.z.wallet.sdk.rpc.DarksideTransactionsURL
	(*DarksideHeight)(nil),          // 4: cash.z.wallet.sdk.rpc.DarksideHeight
	(*DarksideEmptyBlocks)(nil),     // 5: cash.z.wallet.sdk.rpc.DarksideEmptyBlocks
	(*DarksideSubtreeRoots)(nil),    // 6: cash.z.wallet.sdk.rpc.DarksideSubtreeRoots
	(ShieldedProtocol)(0),           // 7: cash.z.wallet.sdk.rpc.ShieldedProtocol
	(*SubtreeRoot)(nil),             // 8: cash.z.wallet.sdk.rpc.SubtreeRoot
	(*RawTransaction)(nil),          // 9: cash.z.wallet.sdk.rpc.RawTransaction
	(*Empty)(nil),                   // 10: cash.z.wallet.sdk.rpc.Empty
	(*GetAddressUtxosReply)(nil),    // 11: cash.z.wallet.sdk.rpc.GetAddressUtxosReply
	(*TreeState)(nil),               // 12: cash.z.wallet.sdk.rpc.TreeState
	(*BlockID)(nil),                 // 13: cash.z.wallet.sdk.rpc.BlockID
}
var file_darkside_proto_depIdxs = []int32{
	7,  // 0: cash.z.wallet.sdk.rpc.DarksideSubtreeRoots.shieldedProtocol:type_name -> cash.z.wallet.sdk.rpc.ShieldedProtocol
	8,  // 1: cash.z.wallet.sdk.rpc.DarksideSubtreeRoots.subtreeRoots:type_name -> cash.z.wallet.sdk.rpc.SubtreeRoot
	0,  // 2: cash.z.wallet.sdk.rpc.DarksideStreamer.Reset:input_type -> cash.z.wallet.sdk.rpc.DarksideMetaState
	1,  // 3: cash.z.wallet.sdk.rpc.DarksideStreamer.StageBlocksStream:input_type -> cash.z.wallet.sdk.rpc.DarksideBlock
	2,  // 4: cash.z.wallet.sdk.rpc.DarksideStreamer.StageBlocks:input_type -> cash.z.wallet.sdk.rpc.DarksideBlocksURL
	5,  // 5: cash.z.wallet.sdk.rpc.DarksideStreamer.StageBlocksCreate:input_type -> cash.z.wallet.sdk.rpc.DarksideEmptyBlocks
	9,  // 6: cash.z.wallet.sdk.rpc.DarksideStreamer.StageTransactionsStream:input_type -> cash.z.wallet.sdk.rpc.RawTransaction
	3,  // 7: cash.z.wallet.sdk.rpc.DarksideStreamer.StageTransactions:input_type -> cash.z.wallet.sdk.rpc.DarksideTransactionsURL
	4,  // 8: cash.z.wallet.sdk.rpc.DarksideStreamer.ApplyStaged:input_type -> cash.z.wallet.sdk.rpc.DarksideHeight
	10, // 9: cash.z.wallet.sdk.rpc.DarksideStreamer.GetIncomingTransactions:input_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 10: cash.z.wallet.sdk.rpc.DarksideStreamer.ClearIncomingTransactions:input_type -> cash.z.wallet.sdk.rpc.Empty
	11, // 11: cash.z.wallet.sdk.rpc.DarksideStreamer.AddAddressUtxo:input_type -> cash.z.wallet.sdk.rpc.GetAddressUtxosReply
	10, // 12: cash.z.wallet.sdk.rpc.DarksideStreamer.ClearAddressUtxo:input_type -> cash.z.wallet.sdk.rpc.Empty
	12, // 13: cash.z.wallet.sdk.rpc.DarksideStreamer.AddTreeState:input_type -> cash.z.wallet.sdk.rpc.TreeState
	13, // 14: cash.z.wallet.sdk.rpc.DarksideStreamer.RemoveTreeState:input_type -> cash.z.wallet.sdk.rpc.BlockID
	10, // 15: cash.z.wallet.sdk.rpc.DarksideStreamer.ClearAllTreeStates:input_type -> cash.z.wallet.sdk.rpc.Empty
	6,  // 16: cash.z.wallet.sdk.rpc.DarksideStreamer.SetSubtreeRoots:input_type -> cash.z.wallet.sdk.rpc.DarksideSubtreeRoots
	10, // 17: cash.z.wallet.sdk.rpc.DarksideStreamer.Stop:input_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 18: cash.z.wallet.sdk.rpc.DarksideStreamer.Reset:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 19: cash.z.wallet.sdk.rpc.DarksideStreamer.StageBlocksStream:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 20: cash.z.wallet.sdk.rpc.DarksideStreamer.StageBlocks:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 21: cash.z.wallet.sdk.rpc.DarksideStreamer.StageBlocksCreate:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 22: cash.z.wallet.sdk.rpc.DarksideStreamer.StageTransactionsStream:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 23: cash.z.wallet.sdk.rpc.DarksideStreamer.StageTransactions:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 24: cash.z.wallet.sdk.rpc.DarksideStreamer.ApplyStaged:output_type -> cash.z.wallet.sdk.rpc.Empty
	9,  // 25: cash.z.wallet.sdk.rpc.DarksideStreamer.GetIncomingTransactions:output_type -> cash.z.wallet.sdk.rpc.RawTransaction
	10, // 26: cash.z.wallet.sdk.rpc.DarksideStreamer.ClearIncomingTransactions:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 27: cash.z.wallet.sdk.rpc.DarksideStreamer.AddAddressUtxo:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 28: cash.z.wallet.sdk.rpc.DarksideStreamer.ClearAddressUtxo:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 29: cash.z.wallet.sdk.rpc.DarksideStreamer.AddTreeState:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 30: cash.z.wallet.sdk.rpc.DarksideStreamer.RemoveTreeState:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 31: cash.z.wallet.sdk.rpc.DarksideStreamer.ClearAllTreeStates:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 32: cash.z.wallet.sdk.rpc.DarksideStreamer.SetSubtreeRoots:output_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 33: cash.z.wallet.sdk.rpc.DarksideStreamer.Stop:output_type -> cash.z.wallet.sdk.rpc.Empty
	18, // [18:34] is the sub-list for method output_type
	2,  // [2:18] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_darkside_proto_init() }
func file_darkside_proto_init() {
	if File_darkside_proto != nil {
		return
	}
	file_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_darkside_proto_rawDesc), len(file_darkside_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_darkside_proto_goTypes,
		DependencyIndexes: file_darkside_proto_depIdxs,
		MessageInfos:      file_darkside_proto_msgTypes,
	}.Build()
	File_darkside_proto = out.File
	file_darkside_proto_goTypes = nil
	file_darkside_proto_depIdxs = nil
}
