// Copyright (c) 2019-2020 The Zcash developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://www.opensource.org/licenses/mit-license.php .

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: service.proto

package walletrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShieldedProtocol int32

const (
	ShieldedProtocol_sapling ShieldedProtocol = 0
	ShieldedProtocol_orchard ShieldedProtocol = 1
)

// Enum value maps for ShieldedProtocol.
var (
	ShieldedProtocol_name = map[int32]string{
		0: "sapling",
		1: "orchard",
	}
	ShieldedProtocol_value = map[string]int32{
		"sapling": 0,
		"orchard": 1,
	}
)

func (x ShieldedProtocol) Enum() *ShieldedProtocol {
	p := new(ShieldedProtocol)
	*p = x
	return p
}

func (x ShieldedProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShieldedProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (ShieldedProtocol) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x ShieldedProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShieldedProtocol.Descriptor instead.
func (ShieldedProtocol) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

// A BlockID message contains identifiers to select a block: a height or a
// hash. Specification by hash is not implemented, but may be in the future.
type BlockID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockID) Reset() {
	*x = BlockID{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockID) ProtoMessage() {}

func (x *BlockID) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockID.ProtoReflect.Descriptor instead.
func (*BlockID) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *BlockID) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockID) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// BlockRange specifies a series of blocks from start to end inclusive.
// Both BlockIDs must be heights; specification by hash is not yet supported.
type BlockRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *BlockID               `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *BlockID               `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRange) Reset() {
	*x = BlockRange{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRange) ProtoMessage() {}

func (x *BlockRange) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRange.ProtoReflect.Descriptor instead.
func (*BlockRange) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *BlockRange) GetStart() *BlockID {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *BlockRange) GetEnd() *BlockID {
	if x != nil {
		return x.End
	}
	return nil
}

// A TxFilter contains the information needed to identify a particular
// transaction: either a block and an index, or a direct transaction hash.
// Currently, only specification by hash is supported.
type TxFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *BlockID               `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`  // block identifier, height or hash
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // index within the block
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`    // transaction ID (hash, txid)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxFilter) Reset() {
	*x = TxFilter{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxFilter) ProtoMessage() {}

func (x *TxFilter) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxFilter.ProtoReflect.Descriptor instead.
func (*TxFilter) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *TxFilter) GetBlock() *BlockID {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *TxFilter) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TxFilter) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// RawTransaction contains the complete transaction data. It also includes the
// height for the block in which the transaction was included in the main
// chain, if any (as detailed below).
type RawTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The serialized representation of the Zcash transaction.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The height at which the transaction is mined, or a sentinel value.
	//
	// Due to an error in the original protobuf definition, it is necessary to
	// reinterpret the result of the `getrawtransaction` RPC call. Zcashd will
	// return the int64 value `-1` for the height of transactions that appear
	// in the block index, but which are not mined in the main chain. Here, the
	// height field of `RawTransaction` was erroneously created as a `uint64`,
	// and as such we must map the response from the zcashd RPC API to be
	// representable within this space. Additionally, the `height` field will
	// be absent for transactions in the mempool, resulting in the default
	// value of `0` being set. Therefore, the meanings of the `height` field of
	// the `RawTransaction` type are as follows:
	//
	//   - height 0: the transaction is in the mempool
	//   - height 0xffffffffffffffff: the transaction has been mined on a fork that
	//     is not currently the main chain
	//   - any other height: the transaction has been mined in the main chain at the
	//     given height
	Height        uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawTransaction) Reset() {
	*x = RawTransaction{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTransaction) ProtoMessage() {}

func (x *RawTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTransaction.ProtoReflect.Descriptor instead.
func (*RawTransaction) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *RawTransaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RawTransaction) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// A SendResponse encodes an error code and a string. It is currently used
// only by SendTransaction(). If error code is zero, the operation was
// successful; if non-zero, it and the message specify the failure.
type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *SendResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *SendResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Chainspec is a placeholder to allow specification of a particular chain fork.
type ChainSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainSpec) Reset() {
	*x = ChainSpec{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSpec) ProtoMessage() {}

func (x *ChainSpec) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSpec.ProtoReflect.Descriptor instead.
func (*ChainSpec) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

// Empty is for gRPCs that take no arguments, currently only GetLightdInfo.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

// LightdInfo returns various information about this lightwalletd instance
// and the state of the blockchain.
type LightdInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Version                 string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Vendor                  string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	TaddrSupport            bool                   `protobuf:"varint,3,opt,name=taddrSupport,proto3" json:"taddrSupport,omitempty"`                       // true
	ChainName               string                 `protobuf:"bytes,4,opt,name=chainName,proto3" json:"chainName,omitempty"`                              // either "main" or "test"
	SaplingActivationHeight uint64                 `protobuf:"varint,5,opt,name=saplingActivationHeight,proto3" json:"saplingActivationHeight,omitempty"` // depends on mainnet or testnet
	ConsensusBranchId       string                 `protobuf:"bytes,6,opt,name=consensusBranchId,proto3" json:"consensusBranchId,omitempty"`              // protocol identifier, see consensus/upgrades.cpp
	BlockHeight             uint64                 `protobuf:"varint,7,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`                         // latest block on the best chain
	GitCommit               string                 `protobuf:"bytes,8,opt,name=gitCommit,proto3" json:"gitCommit,omitempty"`
	Branch                  string                 `protobuf:"bytes,9,opt,name=branch,proto3" json:"branch,omitempty"`
	BuildDate               string                 `protobuf:"bytes,10,opt,name=buildDate,proto3" json:"buildDate,omitempty"`
	BuildUser               string                 `protobuf:"bytes,11,opt,name=buildUser,proto3" json:"buildUser,omitempty"`
	EstimatedHeight         uint64                 `protobuf:"varint,12,opt,name=estimatedHeight,proto3" json:"estimatedHeight,omitempty"`  // less than tip height if zcashd is syncing
	ZcashdBuild             string                 `protobuf:"bytes,13,opt,name=zcashdBuild,proto3" json:"zcashdBuild,omitempty"`           // example: "v4.1.1-877212414"
	ZcashdSubversion        string                 `protobuf:"bytes,14,opt,name=zcashdSubversion,proto3" json:"zcashdSubversion,omitempty"` // example: "/MagicBean:4.1.1/"
	DonationAddress         string                 `protobuf:"bytes,15,opt,name=donationAddress,proto3" json:"donationAddress,omitempty"`   // Zcash donation UA address
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LightdInfo) Reset() {
	*x = LightdInfo{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightdInfo) ProtoMessage() {}

func (x *LightdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightdInfo.ProtoReflect.Descriptor instead.
func (*LightdInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *LightdInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LightdInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *LightdInfo) GetTaddrSupport() bool {
	if x != nil {
		return x.TaddrSupport
	}
	return false
}

func (x *LightdInfo) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *LightdInfo) GetSaplingActivationHeight() uint64 {
	if x != nil {
		return x.SaplingActivationHeight
	}
	return 0
}

func (x *LightdInfo) GetConsensusBranchId() string {
	if x != nil {
		return x.ConsensusBranchId
	}
	return ""
}

func (x *LightdInfo) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *LightdInfo) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *LightdInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *LightdInfo) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *LightdInfo) GetBuildUser() string {
	if x != nil {
		return x.BuildUser
	}
	return ""
}

func (x *LightdInfo) GetEstimatedHeight() uint64 {
	if x != nil {
		return x.EstimatedHeight
	}
	return 0
}

func (x *LightdInfo) GetZcashdBuild() string {
	if x != nil {
		return x.ZcashdBuild
	}
	return ""
}

func (x *LightdInfo) GetZcashdSubversion() string {
	if x != nil {
		return x.ZcashdSubversion
	}
	return ""
}

func (x *LightdInfo) GetDonationAddress() string {
	if x != nil {
		return x.DonationAddress
	}
	return ""
}

// TransparentAddressBlockFilter restricts the results to the given address
// or block range.
type TransparentAddressBlockFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // t-address
	Range         *BlockRange            `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`     // start, end heights
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransparentAddressBlockFilter) Reset() {
	*x = TransparentAddressBlockFilter{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransparentAddressBlockFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransparentAddressBlockFilter) ProtoMessage() {}

func (x *TransparentAddressBlockFilter) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransparentAddressBlockFilter.ProtoReflect.Descriptor instead.
func (*TransparentAddressBlockFilter) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *TransparentAddressBlockFilter) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TransparentAddressBlockFilter) GetRange() *BlockRange {
	if x != nil {
		return x.Range
	}
	return nil
}

// Duration is currently used only for testing, so that the Ping rpc
// can simulate a delay, to create many simultaneous connections. Units
// are microseconds.
type Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntervalUs    int64                  `protobuf:"varint,1,opt,name=intervalUs,proto3" json:"intervalUs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *Duration) GetIntervalUs() int64 {
	if x != nil {
		return x.IntervalUs
	}
	return 0
}

// PingResponse is used to indicate concurrency, how many Ping rpcs
// are executing upon entry and upon exit (after the delay).
// This rpc is used for testing only.
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         int64                  `protobuf:"varint,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Exit          int64                  `protobuf:"varint,2,opt,name=exit,proto3" json:"exit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetEntry() int64 {
	if x != nil {
		return x.Entry
	}
	return 0
}

func (x *PingResponse) GetExit() int64 {
	if x != nil {
		return x.Exit
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AddressList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressList) Reset() {
	*x = AddressList{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressList) ProtoMessage() {}

func (x *AddressList) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressList.ProtoReflect.Descriptor instead.
func (*AddressList) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddressList) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValueZat      int64                  `protobuf:"varint,1,opt,name=valueZat,proto3" json:"valueZat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *Balance) GetValueZat() int64 {
	if x != nil {
		return x.ValueZat
	}
	return 0
}

// The a shortened transaction ID is the prefix in big-endian (hex) format
// (then converted to binary).
type Exclude struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          [][]byte               `protobuf:"bytes,1,rep,name=txid,proto3" json:"txid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exclude) Reset() {
	*x = Exclude{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exclude) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exclude) ProtoMessage() {}

func (x *Exclude) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exclude.ProtoReflect.Descriptor instead.
func (*Exclude) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *Exclude) GetTxid() [][]byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

// The TreeState is derived from the Zcash z_gettreestate rpc.
type TreeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`         // "main" or "test"
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`          // block height
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`               // block id
	Time          uint32                 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`              // Unix epoch time when the block was mined
	SaplingTree   string                 `protobuf:"bytes,5,opt,name=saplingTree,proto3" json:"saplingTree,omitempty"` // sapling commitment tree state
	OrchardTree   string                 `protobuf:"bytes,6,opt,name=orchardTree,proto3" json:"orchardTree,omitempty"` // orchard commitment tree state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeState) Reset() {
	*x = TreeState{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeState) ProtoMessage() {}

func (x *TreeState) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeState.ProtoReflect.Descriptor instead.
func (*TreeState) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *TreeState) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *TreeState) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TreeState) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TreeState) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *TreeState) GetSaplingTree() string {
	if x != nil {
		return x.SaplingTree
	}
	return ""
}

func (x *TreeState) GetOrchardTree() string {
	if x != nil {
		return x.OrchardTree
	}
	return ""
}

type GetSubtreeRootsArg struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StartIndex       uint32                 `protobuf:"varint,1,opt,name=startIndex,proto3" json:"startIndex,omitempty"`                                                         // Index identifying where to start returning subtree roots
	ShieldedProtocol ShieldedProtocol       `protobuf:"varint,2,opt,name=shieldedProtocol,proto3,enum=cash.z.wallet.sdk.rpc.ShieldedProtocol" json:"shieldedProtocol,omitempty"` // Shielded protocol to return subtree roots for
	MaxEntries       uint32                 `protobuf:"varint,3,opt,name=maxEntries,proto3" json:"maxEntries,omitempty"`                                                         // Maximum number of entries to return, or 0 for all entries.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSubtreeRootsArg) Reset() {
	*x = GetSubtreeRootsArg{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubtreeRootsArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubtreeRootsArg) ProtoMessage() {}

func (x *GetSubtreeRootsArg) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubtreeRootsArg.ProtoReflect.Descriptor instead.
func (*GetSubtreeRootsArg) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetSubtreeRootsArg) GetStartIndex() uint32 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *GetSubtreeRootsArg) GetShieldedProtocol() ShieldedProtocol {
	if x != nil {
		return x.ShieldedProtocol
	}
	return ShieldedProtocol_sapling
}

func (x *GetSubtreeRootsArg) GetMaxEntries() uint32 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

type SubtreeRoot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RootHash              []byte                 `protobuf:"bytes,2,opt,name=rootHash,proto3" json:"rootHash,omitempty"`                            // The 32-byte Merkle root of the subtree.
	CompletingBlockHash   []byte                 `protobuf:"bytes,3,opt,name=completingBlockHash,proto3" json:"completingBlockHash,omitempty"`      // The hash of the block that completed this subtree.
	CompletingBlockHeight uint64                 `protobuf:"varint,4,opt,name=completingBlockHeight,proto3" json:"completingBlockHeight,omitempty"` // The height of the block that completed this subtree in the main chain.
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SubtreeRoot) Reset() {
	*x = SubtreeRoot{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtreeRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtreeRoot) ProtoMessage() {}

func (x *SubtreeRoot) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtreeRoot.ProtoReflect.Descriptor instead.
func (*SubtreeRoot) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *SubtreeRoot) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *SubtreeRoot) GetCompletingBlockHash() []byte {
	if x != nil {
		return x.CompletingBlockHash
	}
	return nil
}

func (x *SubtreeRoot) GetCompletingBlockHeight() uint64 {
	if x != nil {
		return x.CompletingBlockHeight
	}
	return 0
}

// Results are sorted by height, which makes it easy to issue another
// request that picks up from where the previous left off.
type GetAddressUtxosArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	StartHeight   uint64                 `protobuf:"varint,2,opt,name=startHeight,proto3" json:"startHeight,omitempty"`
	MaxEntries    uint32                 `protobuf:"varint,3,opt,name=maxEntries,proto3" json:"maxEntries,omitempty"` // zero means unlimited
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressUtxosArg) Reset() {
	*x = GetAddressUtxosArg{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressUtxosArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressUtxosArg) ProtoMessage() {}

func (x *GetAddressUtxosArg) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressUtxosArg.ProtoReflect.Descriptor instead.
func (*GetAddressUtxosArg) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetAddressUtxosArg) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GetAddressUtxosArg) GetStartHeight() uint64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *GetAddressUtxosArg) GetMaxEntries() uint32 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

type GetAddressUtxosReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Txid          []byte                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Script        []byte                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	ValueZat      int64                  `protobuf:"varint,4,opt,name=valueZat,proto3" json:"valueZat,omitempty"`
	Height        uint64                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressUtxosReply) Reset() {
	*x = GetAddressUtxosReply{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressUtxosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressUtxosReply) ProtoMessage() {}

func (x *GetAddressUtxosReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressUtxosReply.ProtoReflect.Descriptor instead.
func (*GetAddressUtxosReply) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetAddressUtxosReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetAddressUtxosReply) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *GetAddressUtxosReply) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GetAddressUtxosReply) GetScript() []byte {
	if x != nil {
		return x.Script
	}
	return nil
}

func (x *GetAddressUtxosReply) GetValueZat() int64 {
	if x != nil {
		return x.ValueZat
	}
	return 0
}

func (x *GetAddressUtxosReply) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetAddressUtxosReplyList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AddressUtxos  []*GetAddressUtxosReply `protobuf:"bytes,1,rep,name=addressUtxos,proto3" json:"addressUtxos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressUtxosReplyList) Reset() {
	*x = GetAddressUtxosReplyList{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressUtxosReplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressUtxosReplyList) ProtoMessage() {}

func (x *GetAddressUtxosReplyList) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressUtxosReplyList.ProtoReflect.Descriptor instead.
func (*GetAddressUtxosReplyList) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetAddressUtxosReplyList) GetAddressUtxos() []*GetAddressUtxosReply {
	if x != nil {
		return x.AddressUtxos
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x15cash.z.wallet.sdk.rpc\x1a\x15compact_formats.proto\"5\n" +
	"\aBlockID\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"t\n" +
	"\n" +
	"BlockRange\x124\n" +
	"\x05start\x18\x01 \x01(\v2\x1e.cash.z.wallet.sdk.rpc.BlockIDR\x05start\x120\n" +
	"\x03end\x18\x02 \x01(\v2\x1e.cash.z.wallet.sdk.rpc.BlockIDR\x03end\"j\n" +
	"\bTxFilter\x124\n" +
	"\x05block\x18\x01 \x01(\v2\x1e.cash.z.wallet.sdk.rpc.BlockIDR\x05block\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\"<\n" +
	"\x0eRawTransaction\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\"P\n" +
	"\fSendResponse\x12\x1c\n" +
	"\terrorCode\x18\x01 \x01(\x05R\terrorCode\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage\"\v\n" +
	"\tChainSpec\"\a\n" +
	"\x05Empty\"\x9e\x04\n" +
	"\n" +
	"LightdInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\"\n" +
	"\ftaddrSupport\x18\x03 \x01(\bR\ftaddrSupport\x12\x1c\n" +
	"\tchainName\x18\x04 \x01(\tR\tchainName\x128\n" +
	"\x17saplingActivationHeight\x18\x05 \x01(\x04R\x17saplingActivationHeight\x12,\n" +
	"\x11consensusBranchId\x18\x06 \x01(\tR\x11consensusBranchId\x12 \n" +
	"\vblockHeight\x18\a \x01(\x04R\vblockHeight\x12\x1c\n" +
	"\tgitCommit\x18\b \x01(\tR\tgitCommit\x12\x16\n" +
	"\x06branch\x18\t \x01(\tR\x06branch\x12\x1c\n" +
	"\tbuildDate\x18\n" +
	" \x01(\tR\tbuildDate\x12\x1c\n" +
	"\tbuildUser\x18\v \x01(\tR\tbuildUser\x12(\n" +
	"\x0festimatedHeight\x18\f \x01(\x04R\x0festimatedHeight\x12 \n" +
	"\vzcashdBuild\x18\r \x01(\tR\vzcashdBuild\x12*\n" +
	"\x10zcashdSubversion\x18\x0e \x01(\tR\x10zcashdSubversion\x12(\n" +
	"\x0fdonationAddress\x18\x0f \x01(\tR\x0fdonationAddress\"r\n" +
	"\x1dTransparentAddressBlockFilter\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x127\n" +
	"\x05range\x18\x02 \x01(\v2!.cash.z.wallet.sdk.rpc.BlockRangeR\x05range\"*\n" +
	"\bDuration\x12\x1e\n" +
	"\n" +
	"intervalUs\x18\x01 \x01(\x03R\n" +
	"intervalUs\"8\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\x03R\x05entry\x12\x12\n" +
	"\x04exit\x18\x02 \x01(\x03R\x04exit\"#\n" +
	"\aAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"+\n" +
	"\vAddressList\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\"%\n" +
	"\aBalance\x12\x1a\n" +
	"\bvalueZat\x18\x01 \x01(\x03R\bvalueZat\"\x1d\n" +
	"\aExclude\x12\x12\n" +
	"\x04txid\x18\x01 \x03(\fR\x04txid\"\xa9\x01\n" +
	"\tTreeState\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x12\n" +
	"\x04time\x18\x04 \x01(\rR\x04time\x12 \n" +
	"\vsaplingTree\x18\x05 \x01(\tR\vsaplingTree\x12 \n" +
	"\vorchardTree\x18\x06 \x01(\tR\vorchardTree\"\xa9\x01\n" +
	"\x12GetSubtreeRootsArg\x12\x1e\n" +
	"\n" +
	"startIndex\x18\x01 \x01(\rR\n" +
	"startIndex\x12S\n" +
	"\x10shieldedProtocol\x18\x02 \x01(\x0e2'.cash.z.wallet.sdk.rpc.ShieldedProtocolR\x10shieldedProtocol\x12\x1e\n" +
	"\n" +
	"maxEntries\x18\x03 \x01(\rR\n" +
	"maxEntries\"\x91\x01\n" +
	"\vSubtreeRoot\x12\x1a\n" +
	"\brootHash\x18\x02 \x01(\fR\brootHash\x120\n" +
	"\x13completingBlockHash\x18\x03 \x01(\fR\x13completingBlockHash\x124\n" +
	"\x15completingBlockHeight\x18\x04 \x01(\x04R\x15completingBlockHeight\"t\n" +
	"\x12GetAddressUtxosArg\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12 \n" +
	"\vstartHeight\x18\x02 \x01(\x04R\vstartHeight\x12\x1e\n" +
	"\n" +
	"maxEntries\x18\x03 \x01(\rR\n" +
	"maxEntries\"\xa6\x01\n" +
	"\x14GetAddressUtxosReply\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x16\n" +
	"\x06script\x18\x03 \x01(\fR\x06script\x12\x1a\n" +
	"\bvalueZat\x18\x04 \x01(\x03R\bvalueZat\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x04R\x06height\"k\n" +
	"\x18GetAddressUtxosReplyList\x12O\n" +
	"\faddressUtxos\x18\x01 \x03(\v2+.cash.z.wallet.sdk.rpc.GetAddressUtxosReplyR\faddressUtxos*,\n" +
	"\x10ShieldedProtocol\x12\v\n" +
	"\asapling\x10\x00\x12\v\n" +
	"\aorchard\x10\x012\x96\x0f\n" +
	"\x11CompactTxStreamer\x12T\n" +
	"\x0eGetLatestBlock\x12 .cash.z.wallet.sdk.rpc.ChainSpec\x1a\x1e.cash.z.wallet.sdk.rpc.BlockID\"\x00\x12Q\n" +
	"\bGetBlock\x12\x1e.cash.z.wallet.sdk.rpc.BlockID\x1a#.cash.z.wallet.sdk.rpc.CompactBlock\"\x00\x12[\n" +
	"\x12GetBlockNullifiers\x12\x1e.cash.z.wallet.sdk.rpc.BlockID\x1a#.cash.z.wallet.sdk.rpc.CompactBlock\"\x00\x12[\n" +
	"\rGetBlockRange\x12!.cash.z.wallet.sdk.rpc.BlockRange\x1a#.cash.z.wallet.sdk.rpc.CompactBlock\"\x000\x01\x12e\n" +
	"\x17GetBlockRangeNullifiers\x12!.cash.z.wallet.sdk.rpc.BlockRange\x1a#.cash.z.wallet.sdk.rpc.CompactBlock\"\x000\x01\x12Z\n" +
	"\x0eGetTransaction\x12\x1f.cash.z.wallet.sdk.rpc.TxFilter\x1a%.cash.z.wallet.sdk.rpc.RawTransaction\"\x00\x12_\n" +
	"\x0fSendTransaction\x12%.cash.z.wallet.sdk.rpc.RawTransaction\x1a#.cash.z.wallet.sdk.rpc.SendResponse\"\x00\x12s\n" +
	"\x10GetTaddressTxids\x124.cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter\x1a%.cash.z.wallet.sdk.rpc.RawTransaction\"\x000\x01\x12z\n" +
	"\x17GetTaddressTransactions\x124.cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter\x1a%.cash.z.wallet.sdk.rpc.RawTransaction\"\x000\x01\x12Z\n" +
	"\x12GetTaddressBalance\x12\".cash.z.wallet.sdk.rpc.AddressList\x1a\x1e.cash.z.wallet.sdk.rpc.Balance\"\x00\x12^\n" +
	"\x18GetTaddressBalanceStream\x12\x1e.cash.z.wallet.sdk.rpc.Address\x1a\x1e.cash.z.wallet.sdk.rpc.Balance\"\x00(\x01\x12T\n" +
	"\fGetMempoolTx\x12\x1e.cash.z.wallet.sdk.rpc.Exclude\x1a .cash.z.wallet.sdk.rpc.CompactTx\"\x000\x01\x12[\n" +
	"\x10GetMempoolStream\x12\x1c.cash.z.wallet.sdk.rpc.Empty\x1a%.cash.z.wallet.sdk.rpc.RawTransaction\"\x000\x01\x12R\n" +
	"\fGetTreeState\x12\x1e.cash.z.wallet.sdk.rpc.BlockID\x1a .cash.z.wallet.sdk.rpc.TreeState\"\x00\x12V\n" +
	"\x12GetLatestTreeState\x12\x1c.cash.z.wallet.sdk.rpc.Empty\x1a .cash.z.wallet.sdk.rpc.TreeState\"\x00\x12d\n" +
	"\x0fGetSubtreeRoots\x12).cash.z.wallet.sdk.rpc.GetSubtreeRootsArg\x1a\".cash.z.wallet.sdk.rpc.SubtreeRoot\"\x000\x01\x12o\n" +
	"\x0fGetAddressUtxos\x12).cash.z.wallet.sdk.rpc.GetAddressUtxosArg\x1a/.cash.z.wallet.sdk.rpc.GetAddressUtxosReplyList\"\x00\x12s\n" +
	"\x15GetAddressUtxosStream\x12).cash.z.wallet.sdk.rpc.GetAddressUtxosArg\x1a+.cash.z.wallet.sdk.rpc.GetAddressUtxosReply\"\x000\x01\x12R\n" +
	"\rGetLightdInfo\x12\x1c.cash.z.wallet.sdk.rpc.Empty\x1a!.cash.z.wallet.sdk.rpc.LightdInfo\"\x00\x12N\n" +
	"\x04Ping\x12\x1f.cash.z.wallet.sdk.rpc.Duration\x1a#.cash.z.wallet.sdk.rpc.PingResponse\"\x00B\x1bZ\x16lightwalletd/walletrpc\xba\x02\x00b\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_service_proto_goTypes = []any{
	(ShieldedProtocol)(0),                 // 0: cash.z.wallet.sdk.rpc.ShieldedProtocol
	(*BlockID)(nil),                       // 1: cash.z.wallet.sdk.rpc.BlockID
	(*BlockRange)(nil),                    // 2: cash.z.wallet.sdk.rpc.BlockRange
	(*TxFilter)(nil),                      // 3: cash.z.wallet.sdk.rpc.TxFilter
	(*RawTransaction)(nil),                // 4: cash.z.wallet.sdk.rpc.RawTransaction
	(*SendResponse)(nil),                  // 5: cash.z.wallet.sdk.rpc.SendResponse
	(*ChainSpec)(nil),                     // 6: cash.z.wallet.sdk.rpc.ChainSpec
	(*Empty)(nil),                         // 7: cash.z.wallet.sdk.rpc.Empty
	(*LightdInfo)(nil),                    // 8: cash.z.wallet.sdk.rpc.LightdInfo
	(*TransparentAddressBlockFilter)(nil), // 9: cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter
	(*Duration)(nil),                      // 10: cash.z.wallet.sdk.rpc.Duration
	(*PingResponse)(nil),                  // 11: cash.z.wallet.sdk.rpc.PingResponse
	(*Address)(nil),                       // 12: cash.z.wallet.sdk.rpc.Address
	(*AddressList)(nil),                   // 13: cash.z.wallet.sdk.rpc.AddressList
	(*Balance)(nil),                       // 14: cash.z.wallet.sdk.rpc.Balance
	(*Exclude)(nil),                       // 15: cash.z.wallet.sdk.rpc.Exclude
	(*TreeState)(nil),                     // 16: cash.z.wallet.sdk.rpc.TreeState
	(*GetSubtreeRootsArg)(nil),            // 17: cash.z.wallet.sdk.rpc.GetSubtreeRootsArg
	(*SubtreeRoot)(nil),                   // 18: cash.z.wallet.sdk.rpc.SubtreeRoot
	(*GetAddressUtxosArg)(nil),            // 19: cash.z.wallet.sdk.rpc.GetAddressUtxosArg
	(*GetAddressUtxosReply)(nil),          // 20: cash.z.wallet.sdk.rpc.GetAddressUtxosReply
	(*GetAddressUtxosReplyList)(nil),      // 21: cash.z.wallet.sdk.rpc.GetAddressUtxosReplyList
	(*CompactBlock)(nil),                  // 22: cash.z.wallet.sdk.rpc.CompactBlock
	(*CompactTx)(nil),                     // 23: cash.z.wallet.sdk.rpc.CompactTx
}
var file_service_proto_depIdxs = []int32{
	1,  // 0: cash.z.wallet.sdk.rpc.BlockRange.start:type_name -> cash.z.wallet.sdk.rpc.BlockID
	1,  // 1: cash.z.wallet.sdk.rpc.BlockRange.end:type_name -> cash.z.wallet.sdk.rpc.BlockID
	1,  // 2: cash.z.wallet.sdk.rpc.TxFilter.block:type_name -> cash.z.wallet.sdk.rpc.BlockID
	2,  // 3: cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter.range:type_name -> cash.z.wallet.sdk.rpc.BlockRange
	0,  // 4: cash.z.wallet.sdk.rpc.GetSubtreeRootsArg.shieldedProtocol:type_name -> cash.z.wallet.sdk.rpc.ShieldedProtocol
	20, // 5: cash.z.wallet.sdk.rpc.GetAddressUtxosReplyList.addressUtxos:type_name -> cash.z.wallet.sdk.rpc.GetAddressUtxosReply
	6,  // 6: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLatestBlock:input_type -> cash.z.wallet.sdk.rpc.ChainSpec
	1,  // 7: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlock:input_type -> cash.z.wallet.sdk.rpc.BlockID
	1,  // 8: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockNullifiers:input_type -> cash.z.wallet.sdk.rpc.BlockID
	2,  // 9: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockRange:input_type -> cash.z.wallet.sdk.rpc.BlockRange
	2,  // 10: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockRangeNullifiers:input_type -> cash.z.wallet.sdk.rpc.BlockRange
	3,  // 11: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTransaction:input_type -> cash.z.wallet.sdk.rpc.TxFilter
	4,  // 12: cash.z.wallet.sdk.rpc.CompactTxStreamer.SendTransaction:input_type -> cash.z.wallet.sdk.rpc.RawTransaction
	9,  // 13: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressTxids:input_type -> cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter
	9,  // 14: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressTransactions:input_type -> cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter
	13, // 15: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressBalance:input_type -> cash.z.wallet.sdk.rpc.AddressList
	12, // 16: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressBalanceStream:input_type -> cash.z.wallet.sdk.rpc.Address
	15, // 17: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetMempoolTx:input_type -> cash.z.wallet.sdk.rpc.Exclude
	7,  // 18: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetMempoolStream:input_type -> cash.z.wallet.sdk.rpc.Empty
	1,  // 19: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTreeState:input_type -> cash.z.wallet.sdk.rpc.BlockID
	7,  // 20: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLatestTreeState:input_type -> cash.z.wallet.sdk.rpc.Empty
	17, // 21: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetSubtreeRoots:input_type -> cash.z.wallet.sdk.rpc.GetSubtreeRootsArg
	19, // 22: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetAddressUtxos:input_type -> cash.z.wallet.sdk.rpc.GetAddressUtxosArg
	19, // 23: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetAddressUtxosStream:input_type -> cash.z.wallet.sdk.rpc.GetAddressUtxosArg
	7,  // 24: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLightdInfo:input_type -> cash.z.wallet.sdk.rpc.Empty
	10, // 25: cash.z.wallet.sdk.rpc.CompactTxStreamer.Ping:input_type -> cash.z.wallet.sdk.rpc.Duration
	1,  // 26: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLatestBlock:output_type -> cash.z.wallet.sdk.rpc.BlockID
	22, // 27: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlock:output_type -> cash.z.wallet.sdk.rpc.CompactBlock
	22, // 28: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockNullifiers:output_type -> cash.z.wallet.sdk.rpc.CompactBlock
	22, // 29: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockRange:output_type -> cash.z.wallet.sdk.rpc.CompactBlock
	22, // 30: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockRangeNullifiers:output_type -> cash.z.wallet.sdk.rpc.CompactBlock
	4,  // 31: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTransaction:output_type -> cash.z.wallet.sdk.rpc.RawTransaction
	5,  // 32: cash.z.wallet.sdk.rpc.CompactTxStreamer.SendTransaction:output_type -> cash.z.wallet.sdk.rpc.SendResponse
	4,  // 33: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressTxids:output_type -> cash.z.wallet.sdk.rpc.RawTransaction
	4,  // 34: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressTransactions:output_type -> cash.z.wallet.sdk.rpc.RawTransaction
	14, // 35: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressBalance:output_type -> cash.z.wallet.sdk.rpc.Balance
	14, // 36: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressBalanceStream:output_type -> cash.z.wallet.sdk.rpc.Balance
	23, // 37: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetMempoolTx:output_type -> cash.z.wallet.sdk.rpc.CompactTx
	4,  // 38: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetMempoolStream:output_type -> cash.z.wallet.sdk.rpc.RawTransaction
	16, // 39: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTreeState:output_type -> cash.z.wallet.sdk.rpc.TreeState
	16, // 40: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLatestTreeState:output_type -> cash.z.wallet.sdk.rpc.TreeState
	18, // 41: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetSubtreeRoots:output_type -> cash.z.wallet.sdk.rpc.SubtreeRoot
	21, // 42: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetAddressUtxos:output_type -> cash.z.wallet.sdk.rpc.GetAddressUtxosReplyList
	20, // 43: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetAddressUtxosStream:output_type -> cash.z.wallet.sdk.rpc.GetAddressUtxosReply
	8,  // 44: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLightdInfo:output_type -> cash.z.wallet.sdk.rpc.LightdInfo
	11, // 45: cash.z.wallet.sdk.rpc.CompactTxStreamer.Ping:output_type -> cash.z.wallet.sdk.rpc.PingResponse
	26, // [26:46] is the sub-list for method output_type
	6,  // [6:26] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_compact_formats_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
