// Copyright (c) 2019-2020 The Zcash developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://www.opensource.org/licenses/mit-license.php .

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: service.proto

package walletrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An identifier for a Zcash value pool.
type PoolType int32

const (
	PoolType_POOL_TYPE_INVALID PoolType = 0
	PoolType_TRANSPARENT       PoolType = 1
	PoolType_SAPLING           PoolType = 2
	PoolType_ORCHARD           PoolType = 3
)

// Enum value maps for PoolType.
var (
	PoolType_name = map[int32]string{
		0: "POOL_TYPE_INVALID",
		1: "TRANSPARENT",
		2: "SAPLING",
		3: "ORCHARD",
	}
	PoolType_value = map[string]int32{
		"POOL_TYPE_INVALID": 0,
		"TRANSPARENT":       1,
		"SAPLING":           2,
		"ORCHARD":           3,
	}
)

func (x PoolType) Enum() *PoolType {
	p := new(PoolType)
	*p = x
	return p
}

func (x PoolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PoolType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (PoolType) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x PoolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PoolType.Descriptor instead.
func (PoolType) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type ShieldedProtocol int32

const (
	ShieldedProtocol_sapling ShieldedProtocol = 0
	ShieldedProtocol_orchard ShieldedProtocol = 1
)

// Enum value maps for ShieldedProtocol.
var (
	ShieldedProtocol_name = map[int32]string{
		0: "sapling",
		1: "orchard",
	}
	ShieldedProtocol_value = map[string]int32{
		"sapling": 0,
		"orchard": 1,
	}
)

func (x ShieldedProtocol) Enum() *ShieldedProtocol {
	p := new(ShieldedProtocol)
	*p = x
	return p
}

func (x ShieldedProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShieldedProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[1].Descriptor()
}

func (ShieldedProtocol) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[1]
}

func (x ShieldedProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShieldedProtocol.Descriptor instead.
func (ShieldedProtocol) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

// A BlockID message contains identifiers to select a block: a height or a
// hash. Specification by hash is not implemented, but may be in the future.
type BlockID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockID) Reset() {
	*x = BlockID{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockID) ProtoMessage() {}

func (x *BlockID) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockID.ProtoReflect.Descriptor instead.
func (*BlockID) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *BlockID) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockID) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// BlockRange specifies a series of blocks from start to end inclusive.
// Both BlockIDs must be heights; specification by hash is not yet supported.
//
// If no pool types are specified, the server should default to the legacy
// behavior of returning only data relevant to the shielded (Sapling and
// Orchard) pools; otherwise, the server should prune `CompactBlocks` returned
// to include only data relevant to the requested pool types. Clients MUST
// verify that the version of the server they are connected to are capable
// of returning pruned and/or transparent data before setting `poolTypes`
// to a non-empty value.
type BlockRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *BlockID               `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *BlockID               `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	PoolTypes     []PoolType             `protobuf:"varint,3,rep,packed,name=poolTypes,proto3,enum=cash.z.wallet.sdk.rpc.PoolType" json:"poolTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRange) Reset() {
	*x = BlockRange{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRange) ProtoMessage() {}

func (x *BlockRange) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRange.ProtoReflect.Descriptor instead.
func (*BlockRange) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *BlockRange) GetStart() *BlockID {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *BlockRange) GetEnd() *BlockID {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *BlockRange) GetPoolTypes() []PoolType {
	if x != nil {
		return x.PoolTypes
	}
	return nil
}

// A TxFilter contains the information needed to identify a particular
// transaction: either a block and an index, or a direct transaction hash.
// Currently, only specification by hash is supported.
type TxFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *BlockID               `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`  // block identifier, height or hash
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // index within the block
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`    // transaction ID (hash, txid)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxFilter) Reset() {
	*x = TxFilter{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxFilter) ProtoMessage() {}

func (x *TxFilter) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxFilter.ProtoReflect.Descriptor instead.
func (*TxFilter) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *TxFilter) GetBlock() *BlockID {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *TxFilter) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TxFilter) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// RawTransaction contains the complete transaction data. It also optionally includes
// the block height in which the transaction was included, or, when returned
// by GetMempoolStream(), the latest block height.
//
// FIXME: the documentation here about mempool status contradicts the documentation
// for the `height` field. See https://github.com/zcash/librustzcash/issues/1484
type RawTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The serialized representation of the Zcash transaction.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The height at which the transaction is mined, or a sentinel value.
	//
	// Due to an error in the original protobuf definition, it is necessary to
	// reinterpret the result of the `getrawtransaction` RPC call. Zcashd will
	// return the int64 value `-1` for the height of transactions that appear
	// in the block index, but which are not mined in the main chain. Here, the
	// height field of `RawTransaction` was erroneously created as a `uint64`,
	// and as such we must map the response from the zcashd RPC API to be
	// representable within this space. Additionally, the `height` field will
	// be absent for transactions in the mempool, resulting in the default
	// value of `0` being set. Therefore, the meanings of the `height` field of
	// the `RawTransaction` type are as follows:
	//
	//   - height 0: the transaction is in the mempool
	//   - height 0xffffffffffffffff: the transaction has been mined on a fork that
	//     is not currently the main chain
	//   - any other height: the transaction has been mined in the main chain at the
	//     given height
	Height        uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawTransaction) Reset() {
	*x = RawTransaction{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTransaction) ProtoMessage() {}

func (x *RawTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTransaction.ProtoReflect.Descriptor instead.
func (*RawTransaction) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *RawTransaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RawTransaction) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// A SendResponse encodes an error code and a string. It is currently used
// only by SendTransaction(). If error code is zero, the operation was
// successful; if non-zero, it and the message specify the failure.
type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     int32                  `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *SendResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *SendResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Chainspec is a placeholder to allow specification of a particular chain fork.
type ChainSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainSpec) Reset() {
	*x = ChainSpec{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSpec) ProtoMessage() {}

func (x *ChainSpec) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSpec.ProtoReflect.Descriptor instead.
func (*ChainSpec) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

// Empty is for gRPCs that take no arguments, currently only GetLightdInfo.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

// LightdInfo returns various information about this lightwalletd instance
// and the state of the blockchain.
type LightdInfo struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Version                    string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Vendor                     string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	TaddrSupport               bool                   `protobuf:"varint,3,opt,name=taddrSupport,proto3" json:"taddrSupport,omitempty"`                       // true
	ChainName                  string                 `protobuf:"bytes,4,opt,name=chainName,proto3" json:"chainName,omitempty"`                              // either "main" or "test"
	SaplingActivationHeight    uint64                 `protobuf:"varint,5,opt,name=saplingActivationHeight,proto3" json:"saplingActivationHeight,omitempty"` // depends on mainnet or testnet
	ConsensusBranchId          string                 `protobuf:"bytes,6,opt,name=consensusBranchId,proto3" json:"consensusBranchId,omitempty"`              // protocol identifier, see consensus/upgrades.cpp
	BlockHeight                uint64                 `protobuf:"varint,7,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`                         // latest block on the best chain
	GitCommit                  string                 `protobuf:"bytes,8,opt,name=gitCommit,proto3" json:"gitCommit,omitempty"`
	Branch                     string                 `protobuf:"bytes,9,opt,name=branch,proto3" json:"branch,omitempty"`
	BuildDate                  string                 `protobuf:"bytes,10,opt,name=buildDate,proto3" json:"buildDate,omitempty"`
	BuildUser                  string                 `protobuf:"bytes,11,opt,name=buildUser,proto3" json:"buildUser,omitempty"`
	EstimatedHeight            uint64                 `protobuf:"varint,12,opt,name=estimatedHeight,proto3" json:"estimatedHeight,omitempty"`                      // less than tip height if zcashd is syncing
	ZcashdBuild                string                 `protobuf:"bytes,13,opt,name=zcashdBuild,proto3" json:"zcashdBuild,omitempty"`                               // example: "v4.1.1-877212414"
	ZcashdSubversion           string                 `protobuf:"bytes,14,opt,name=zcashdSubversion,proto3" json:"zcashdSubversion,omitempty"`                     // example: "/MagicBean:4.1.1/"
	DonationAddress            string                 `protobuf:"bytes,15,opt,name=donationAddress,proto3" json:"donationAddress,omitempty"`                       // Zcash donation UA address
	UpgradeName                string                 `protobuf:"bytes,16,opt,name=upgradeName,proto3" json:"upgradeName,omitempty"`                               // name of next pending network upgrade, empty if none scheduled
	UpgradeHeight              uint64                 `protobuf:"varint,17,opt,name=upgradeHeight,proto3" json:"upgradeHeight,omitempty"`                          // height of next pending upgrade, zero if none is scheduled
	LightwalletProtocolVersion string                 `protobuf:"bytes,18,opt,name=lightwalletProtocolVersion,proto3" json:"lightwalletProtocolVersion,omitempty"` // version of https://github.com/zcash/lightwallet-protocol served by this server
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *LightdInfo) Reset() {
	*x = LightdInfo{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightdInfo) ProtoMessage() {}

func (x *LightdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightdInfo.ProtoReflect.Descriptor instead.
func (*LightdInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *LightdInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LightdInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *LightdInfo) GetTaddrSupport() bool {
	if x != nil {
		return x.TaddrSupport
	}
	return false
}

func (x *LightdInfo) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *LightdInfo) GetSaplingActivationHeight() uint64 {
	if x != nil {
		return x.SaplingActivationHeight
	}
	return 0
}

func (x *LightdInfo) GetConsensusBranchId() string {
	if x != nil {
		return x.ConsensusBranchId
	}
	return ""
}

func (x *LightdInfo) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *LightdInfo) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *LightdInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *LightdInfo) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *LightdInfo) GetBuildUser() string {
	if x != nil {
		return x.BuildUser
	}
	return ""
}

func (x *LightdInfo) GetEstimatedHeight() uint64 {
	if x != nil {
		return x.EstimatedHeight
	}
	return 0
}

func (x *LightdInfo) GetZcashdBuild() string {
	if x != nil {
		return x.ZcashdBuild
	}
	return ""
}

func (x *LightdInfo) GetZcashdSubversion() string {
	if x != nil {
		return x.ZcashdSubversion
	}
	return ""
}

func (x *LightdInfo) GetDonationAddress() string {
	if x != nil {
		return x.DonationAddress
	}
	return ""
}

func (x *LightdInfo) GetUpgradeName() string {
	if x != nil {
		return x.UpgradeName
	}
	return ""
}

func (x *LightdInfo) GetUpgradeHeight() uint64 {
	if x != nil {
		return x.UpgradeHeight
	}
	return 0
}

func (x *LightdInfo) GetLightwalletProtocolVersion() string {
	if x != nil {
		return x.LightwalletProtocolVersion
	}
	return ""
}

// TransparentAddressBlockFilter restricts the results of the GRPC methods that
// use it to the transactions that involve the given address and were mined in
// the specified block range. Non-default values for both the address and the
// block range must be specified. Mempool transactions are not included.
//
// The `poolTypes` field of the `range` argument should be ignored.
// Implementations MAY consider it an error if any pool types are specified.
type TransparentAddressBlockFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // t-address
	Range         *BlockRange            `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`     // start, end heights only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransparentAddressBlockFilter) Reset() {
	*x = TransparentAddressBlockFilter{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransparentAddressBlockFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransparentAddressBlockFilter) ProtoMessage() {}

func (x *TransparentAddressBlockFilter) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransparentAddressBlockFilter.ProtoReflect.Descriptor instead.
func (*TransparentAddressBlockFilter) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *TransparentAddressBlockFilter) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TransparentAddressBlockFilter) GetRange() *BlockRange {
	if x != nil {
		return x.Range
	}
	return nil
}

// Duration is currently used only for testing, so that the Ping rpc
// can simulate a delay, to create many simultaneous connections. Units
// are microseconds.
type Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntervalUs    int64                  `protobuf:"varint,1,opt,name=intervalUs,proto3" json:"intervalUs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *Duration) GetIntervalUs() int64 {
	if x != nil {
		return x.IntervalUs
	}
	return 0
}

// PingResponse is used to indicate concurrency, how many Ping rpcs
// are executing upon entry and upon exit (after the delay).
// This rpc is used for testing only.
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         int64                  `protobuf:"varint,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Exit          int64                  `protobuf:"varint,2,opt,name=exit,proto3" json:"exit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetEntry() int64 {
	if x != nil {
		return x.Entry
	}
	return 0
}

func (x *PingResponse) GetExit() int64 {
	if x != nil {
		return x.Exit
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AddressList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressList) Reset() {
	*x = AddressList{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressList) ProtoMessage() {}

func (x *AddressList) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressList.ProtoReflect.Descriptor instead.
func (*AddressList) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddressList) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValueZat      int64                  `protobuf:"varint,1,opt,name=valueZat,proto3" json:"valueZat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *Balance) GetValueZat() int64 {
	if x != nil {
		return x.ValueZat
	}
	return 0
}

// Request parameters for the `GetMempoolTx` RPC.
type GetMempoolTxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of transaction ID byte string suffixes that should be excluded
	// from the response. These suffixes may be produced either directly from
	// the underlying txid bytes, or, if the source values are encoded txid
	// strings, by truncating the hexadecimal representation of each
	// transaction ID to an even number of characters, and then hex-decoding
	// and then byte-reversing this value to obtain the byte representation.
	ExcludeTxidSuffixes [][]byte `protobuf:"bytes,1,rep,name=exclude_txid_suffixes,json=excludeTxidSuffixes,proto3" json:"exclude_txid_suffixes,omitempty"`
	// The server must prune `CompactTx`s returned to include only data
	// relevant to the requested pool types. If no pool types are specified,
	// the server should default to the legacy behavior of returning only data
	// relevant to the shielded (Sapling and Orchard) pools.
	PoolTypes     []PoolType `protobuf:"varint,3,rep,packed,name=poolTypes,proto3,enum=cash.z.wallet.sdk.rpc.PoolType" json:"poolTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMempoolTxRequest) Reset() {
	*x = GetMempoolTxRequest{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMempoolTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMempoolTxRequest) ProtoMessage() {}

func (x *GetMempoolTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMempoolTxRequest.ProtoReflect.Descriptor instead.
func (*GetMempoolTxRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetMempoolTxRequest) GetExcludeTxidSuffixes() [][]byte {
	if x != nil {
		return x.ExcludeTxidSuffixes
	}
	return nil
}

func (x *GetMempoolTxRequest) GetPoolTypes() []PoolType {
	if x != nil {
		return x.PoolTypes
	}
	return nil
}

// The TreeState is derived from the Zcash z_gettreestate rpc.
type TreeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`         // "main" or "test"
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`          // block height
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`               // block id
	Time          uint32                 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`              // Unix epoch time when the block was mined
	SaplingTree   string                 `protobuf:"bytes,5,opt,name=saplingTree,proto3" json:"saplingTree,omitempty"` // sapling commitment tree state
	OrchardTree   string                 `protobuf:"bytes,6,opt,name=orchardTree,proto3" json:"orchardTree,omitempty"` // orchard commitment tree state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeState) Reset() {
	*x = TreeState{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeState) ProtoMessage() {}

func (x *TreeState) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeState.ProtoReflect.Descriptor instead.
func (*TreeState) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *TreeState) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *TreeState) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TreeState) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TreeState) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *TreeState) GetSaplingTree() string {
	if x != nil {
		return x.SaplingTree
	}
	return ""
}

func (x *TreeState) GetOrchardTree() string {
	if x != nil {
		return x.OrchardTree
	}
	return ""
}

type GetSubtreeRootsArg struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StartIndex       uint32                 `protobuf:"varint,1,opt,name=startIndex,proto3" json:"startIndex,omitempty"`                                                         // Index identifying where to start returning subtree roots
	ShieldedProtocol ShieldedProtocol       `protobuf:"varint,2,opt,name=shieldedProtocol,proto3,enum=cash.z.wallet.sdk.rpc.ShieldedProtocol" json:"shieldedProtocol,omitempty"` // Shielded protocol to return subtree roots for
	MaxEntries       uint32                 `protobuf:"varint,3,opt,name=maxEntries,proto3" json:"maxEntries,omitempty"`                                                         // Maximum number of entries to return, or 0 for all entries.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSubtreeRootsArg) Reset() {
	*x = GetSubtreeRootsArg{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubtreeRootsArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubtreeRootsArg) ProtoMessage() {}

func (x *GetSubtreeRootsArg) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubtreeRootsArg.ProtoReflect.Descriptor instead.
func (*GetSubtreeRootsArg) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetSubtreeRootsArg) GetStartIndex() uint32 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *GetSubtreeRootsArg) GetShieldedProtocol() ShieldedProtocol {
	if x != nil {
		return x.ShieldedProtocol
	}
	return ShieldedProtocol_sapling
}

func (x *GetSubtreeRootsArg) GetMaxEntries() uint32 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

type SubtreeRoot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RootHash              []byte                 `protobuf:"bytes,2,opt,name=rootHash,proto3" json:"rootHash,omitempty"`                            // The 32-byte Merkle root of the subtree.
	CompletingBlockHash   []byte                 `protobuf:"bytes,3,opt,name=completingBlockHash,proto3" json:"completingBlockHash,omitempty"`      // The hash of the block that completed this subtree.
	CompletingBlockHeight uint64                 `protobuf:"varint,4,opt,name=completingBlockHeight,proto3" json:"completingBlockHeight,omitempty"` // The height of the block that completed this subtree in the main chain.
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SubtreeRoot) Reset() {
	*x = SubtreeRoot{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtreeRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtreeRoot) ProtoMessage() {}

func (x *SubtreeRoot) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtreeRoot.ProtoReflect.Descriptor instead.
func (*SubtreeRoot) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *SubtreeRoot) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *SubtreeRoot) GetCompletingBlockHash() []byte {
	if x != nil {
		return x.CompletingBlockHash
	}
	return nil
}

func (x *SubtreeRoot) GetCompletingBlockHeight() uint64 {
	if x != nil {
		return x.CompletingBlockHeight
	}
	return 0
}

// Results are sorted by height, which makes it easy to issue another
// request that picks up from where the previous left off.
type GetAddressUtxosArg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	StartHeight   uint64                 `protobuf:"varint,2,opt,name=startHeight,proto3" json:"startHeight,omitempty"`
	MaxEntries    uint32                 `protobuf:"varint,3,opt,name=maxEntries,proto3" json:"maxEntries,omitempty"` // zero means unlimited
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressUtxosArg) Reset() {
	*x = GetAddressUtxosArg{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressUtxosArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressUtxosArg) ProtoMessage() {}

func (x *GetAddressUtxosArg) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressUtxosArg.ProtoReflect.Descriptor instead.
func (*GetAddressUtxosArg) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetAddressUtxosArg) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GetAddressUtxosArg) GetStartHeight() uint64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *GetAddressUtxosArg) GetMaxEntries() uint32 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

type GetAddressUtxosReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Txid          []byte                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Script        []byte                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	ValueZat      int64                  `protobuf:"varint,4,opt,name=valueZat,proto3" json:"valueZat,omitempty"`
	Height        uint64                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressUtxosReply) Reset() {
	*x = GetAddressUtxosReply{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressUtxosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressUtxosReply) ProtoMessage() {}

func (x *GetAddressUtxosReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressUtxosReply.ProtoReflect.Descriptor instead.
func (*GetAddressUtxosReply) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetAddressUtxosReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetAddressUtxosReply) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *GetAddressUtxosReply) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GetAddressUtxosReply) GetScript() []byte {
	if x != nil {
		return x.Script
	}
	return nil
}

func (x *GetAddressUtxosReply) GetValueZat() int64 {
	if x != nil {
		return x.ValueZat
	}
	return 0
}

func (x *GetAddressUtxosReply) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetAddressUtxosReplyList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AddressUtxos  []*GetAddressUtxosReply `protobuf:"bytes,1,rep,name=addressUtxos,proto3" json:"addressUtxos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressUtxosReplyList) Reset() {
	*x = GetAddressUtxosReplyList{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressUtxosReplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressUtxosReplyList) ProtoMessage() {}

func (x *GetAddressUtxosReplyList) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressUtxosReplyList.ProtoReflect.Descriptor instead.
func (*GetAddressUtxosReplyList) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetAddressUtxosReplyList) GetAddressUtxos() []*GetAddressUtxosReply {
	if x != nil {
		return x.AddressUtxos
	}
	return nil
}

// Request for PIR parameters needed by clients to construct queries
type GetPirParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPirParamsRequest) Reset() {
	*x = GetPirParamsRequest{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPirParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPirParamsRequest) ProtoMessage() {}

func (x *GetPirParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPirParamsRequest.ProtoReflect.Descriptor instead.
func (*GetPirParamsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

// Cuckoo hash table parameters
type CuckooParams struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NumBuckets       uint64                 `protobuf:"varint,1,opt,name=numBuckets,proto3" json:"numBuckets,omitempty"`             // Number of buckets in the Cuckoo table
	BucketSize       uint32                 `protobuf:"varint,2,opt,name=bucketSize,proto3" json:"bucketSize,omitempty"`             // Size of each bucket in bytes
	HashSeed         []byte                 `protobuf:"bytes,3,opt,name=hashSeed,proto3" json:"hashSeed,omitempty"`                  // Seed for the hash functions
	NumHashFunctions uint32                 `protobuf:"varint,4,opt,name=numHashFunctions,proto3" json:"numHashFunctions,omitempty"` // Number of hash functions used
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CuckooParams) Reset() {
	*x = CuckooParams{}
	mi := &file_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CuckooParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CuckooParams) ProtoMessage() {}

func (x *CuckooParams) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CuckooParams.ProtoReflect.Descriptor instead.
func (*CuckooParams) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{22}
}

func (x *CuckooParams) GetNumBuckets() uint64 {
	if x != nil {
		return x.NumBuckets
	}
	return 0
}

func (x *CuckooParams) GetBucketSize() uint32 {
	if x != nil {
		return x.BucketSize
	}
	return 0
}

func (x *CuckooParams) GetHashSeed() []byte {
	if x != nil {
		return x.HashSeed
	}
	return nil
}

func (x *CuckooParams) GetNumHashFunctions() uint32 {
	if x != nil {
		return x.NumHashFunctions
	}
	return 0
}

// YPIR-specific parameters
type YpirParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumRows       uint64                 `protobuf:"varint,1,opt,name=numRows,proto3" json:"numRows,omitempty"`         // Number of rows in the PIR database
	NumCols       uint64                 `protobuf:"varint,2,opt,name=numCols,proto3" json:"numCols,omitempty"`         // Number of columns in the PIR database
	ElementSize   uint64                 `protobuf:"varint,3,opt,name=elementSize,proto3" json:"elementSize,omitempty"` // Size of each element in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YpirParams) Reset() {
	*x = YpirParams{}
	mi := &file_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YpirParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YpirParams) ProtoMessage() {}

func (x *YpirParams) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YpirParams.ProtoReflect.Descriptor instead.
func (*YpirParams) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{23}
}

func (x *YpirParams) GetNumRows() uint64 {
	if x != nil {
		return x.NumRows
	}
	return 0
}

func (x *YpirParams) GetNumCols() uint64 {
	if x != nil {
		return x.NumCols
	}
	return 0
}

func (x *YpirParams) GetElementSize() uint64 {
	if x != nil {
		return x.ElementSize
	}
	return 0
}

// InsPIRe-specific parameters (when available)
type InspireParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumRows       uint64                 `protobuf:"varint,1,opt,name=numRows,proto3" json:"numRows,omitempty"`         // Number of rows
	NumCols       uint64                 `protobuf:"varint,2,opt,name=numCols,proto3" json:"numCols,omitempty"`         // Number of columns
	ElementSize   uint64                 `protobuf:"varint,3,opt,name=elementSize,proto3" json:"elementSize,omitempty"` // Element size
	Factor        uint32                 `protobuf:"varint,4,opt,name=factor,proto3" json:"factor,omitempty"`           // InsPIRe factor parameter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspireParams) Reset() {
	*x = InspireParams{}
	mi := &file_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspireParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspireParams) ProtoMessage() {}

func (x *InspireParams) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspireParams.ProtoReflect.Descriptor instead.
func (*InspireParams) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{24}
}

func (x *InspireParams) GetNumRows() uint64 {
	if x != nil {
		return x.NumRows
	}
	return 0
}

func (x *InspireParams) GetNumCols() uint64 {
	if x != nil {
		return x.NumCols
	}
	return 0
}

func (x *InspireParams) GetElementSize() uint64 {
	if x != nil {
		return x.ElementSize
	}
	return 0
}

func (x *InspireParams) GetFactor() uint32 {
	if x != nil {
		return x.Factor
	}
	return 0
}

// Response containing PIR parameters
type PirParamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Height below which clients should use PIR queries
	// Above this height, clients should use trial decryption (GetBlockRangeNullifiers)
	PirCutoffHeight uint64 `protobuf:"varint,1,opt,name=pirCutoffHeight,proto3" json:"pirCutoffHeight,omitempty"`
	// Cuckoo hash table parameters for bucket index calculation
	CuckooParams *CuckooParams `protobuf:"bytes,2,opt,name=cuckooParams,proto3" json:"cuckooParams,omitempty"`
	// YPIR parameters (always available)
	YpirParams *YpirParams `protobuf:"bytes,3,opt,name=ypirParams,proto3" json:"ypirParams,omitempty"`
	// InsPIRe parameters (may be absent if not compiled with inspire feature)
	InspireParams *InspireParams `protobuf:"bytes,4,opt,name=inspireParams,proto3" json:"inspireParams,omitempty"`
	// Total number of nullifiers in the PIR database
	NumNullifiers uint64 `protobuf:"varint,5,opt,name=numNullifiers,proto3" json:"numNullifiers,omitempty"`
	// Whether the PIR service is ready to handle queries
	PirReady      bool `protobuf:"varint,6,opt,name=pirReady,proto3" json:"pirReady,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PirParamsResponse) Reset() {
	*x = PirParamsResponse{}
	mi := &file_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PirParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PirParamsResponse) ProtoMessage() {}

func (x *PirParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PirParamsResponse.ProtoReflect.Descriptor instead.
func (*PirParamsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{25}
}

func (x *PirParamsResponse) GetPirCutoffHeight() uint64 {
	if x != nil {
		return x.PirCutoffHeight
	}
	return 0
}

func (x *PirParamsResponse) GetCuckooParams() *CuckooParams {
	if x != nil {
		return x.CuckooParams
	}
	return nil
}

func (x *PirParamsResponse) GetYpirParams() *YpirParams {
	if x != nil {
		return x.YpirParams
	}
	return nil
}

func (x *PirParamsResponse) GetInspireParams() *InspireParams {
	if x != nil {
		return x.InspireParams
	}
	return nil
}

func (x *PirParamsResponse) GetNumNullifiers() uint64 {
	if x != nil {
		return x.NumNullifiers
	}
	return 0
}

func (x *PirParamsResponse) GetPirReady() bool {
	if x != nil {
		return x.PirReady
	}
	return false
}

// Request to execute a YPIR query
type YpirQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         []byte                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // Serialized YPIR query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YpirQueryRequest) Reset() {
	*x = YpirQueryRequest{}
	mi := &file_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YpirQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YpirQueryRequest) ProtoMessage() {}

func (x *YpirQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YpirQueryRequest.ProtoReflect.Descriptor instead.
func (*YpirQueryRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{26}
}

func (x *YpirQueryRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

// Response from a YPIR query
type YpirQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []byte                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"` // Serialized YPIR response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YpirQueryResponse) Reset() {
	*x = YpirQueryResponse{}
	mi := &file_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YpirQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YpirQueryResponse) ProtoMessage() {}

func (x *YpirQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YpirQueryResponse.ProtoReflect.Descriptor instead.
func (*YpirQueryResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{27}
}

func (x *YpirQueryResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

// Request to execute an InsPIRe query
type InspireQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         []byte                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // Serialized InsPIRe query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspireQueryRequest) Reset() {
	*x = InspireQueryRequest{}
	mi := &file_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspireQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspireQueryRequest) ProtoMessage() {}

func (x *InspireQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspireQueryRequest.ProtoReflect.Descriptor instead.
func (*InspireQueryRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{28}
}

func (x *InspireQueryRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

// Response from an InsPIRe query
type InspireQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      []byte                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"` // Serialized InsPIRe response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspireQueryResponse) Reset() {
	*x = InspireQueryResponse{}
	mi := &file_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspireQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspireQueryResponse) ProtoMessage() {}

func (x *InspireQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspireQueryResponse.ProtoReflect.Descriptor instead.
func (*InspireQueryResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{29}
}

func (x *InspireQueryResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

// Request for PIR service status
type GetPirStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPirStatusRequest) Reset() {
	*x = GetPirStatusRequest{}
	mi := &file_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPirStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPirStatusRequest) ProtoMessage() {}

func (x *GetPirStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPirStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPirStatusRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{30}
}

// Response with PIR service status
type PirStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether PIR service is available
	Available bool `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	// Current status: "ready", "building", "unavailable"
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Height of the current PIR database
	PirDbHeight uint64 `protobuf:"varint,3,opt,name=pirDbHeight,proto3" json:"pirDbHeight,omitempty"`
	// Number of blocks pending processing
	PendingBlocks uint32 `protobuf:"varint,4,opt,name=pendingBlocks,proto3" json:"pendingBlocks,omitempty"`
	// Total number of nullifiers in the database
	NumNullifiers uint64 `protobuf:"varint,5,opt,name=numNullifiers,proto3" json:"numNullifiers,omitempty"`
	// Number of Cuckoo buckets
	NumBuckets uint64 `protobuf:"varint,6,opt,name=numBuckets,proto3" json:"numBuckets,omitempty"`
	// Whether a rebuild is currently in progress
	RebuildInProgress bool `protobuf:"varint,7,opt,name=rebuildInProgress,proto3" json:"rebuildInProgress,omitempty"`
	// Timestamp of the last successful database build (ISO 8601)
	LastBuildTime string `protobuf:"bytes,8,opt,name=lastBuildTime,proto3" json:"lastBuildTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PirStatusResponse) Reset() {
	*x = PirStatusResponse{}
	mi := &file_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PirStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PirStatusResponse) ProtoMessage() {}

func (x *PirStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PirStatusResponse.ProtoReflect.Descriptor instead.
func (*PirStatusResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{31}
}

func (x *PirStatusResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *PirStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PirStatusResponse) GetPirDbHeight() uint64 {
	if x != nil {
		return x.PirDbHeight
	}
	return 0
}

func (x *PirStatusResponse) GetPendingBlocks() uint32 {
	if x != nil {
		return x.PendingBlocks
	}
	return 0
}

func (x *PirStatusResponse) GetNumNullifiers() uint64 {
	if x != nil {
		return x.NumNullifiers
	}
	return 0
}

func (x *PirStatusResponse) GetNumBuckets() uint64 {
	if x != nil {
		return x.NumBuckets
	}
	return 0
}

func (x *PirStatusResponse) GetRebuildInProgress() bool {
	if x != nil {
		return x.RebuildInProgress
	}
	return false
}

func (x *PirStatusResponse) GetLastBuildTime() string {
	if x != nil {
		return x.LastBuildTime
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x15cash.z.wallet.sdk.rpc\x1a\x15compact_formats.proto\"5\n" +
	"\aBlockID\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"\xb3\x01\n" +
	"\n" +
	"BlockRange\x124\n" +
	"\x05start\x18\x01 \x01(\v2\x1e.cash.z.wallet.sdk.rpc.BlockIDR\x05start\x120\n" +
	"\x03end\x18\x02 \x01(\v2\x1e.cash.z.wallet.sdk.rpc.BlockIDR\x03end\x12=\n" +
	"\tpoolTypes\x18\x03 \x03(\x0e2\x1f.cash.z.wallet.sdk.rpc.PoolTypeR\tpoolTypes\"j\n" +
	"\bTxFilter\x124\n" +
	"\x05block\x18\x01 \x01(\v2\x1e.cash.z.wallet.sdk.rpc.BlockIDR\x05block\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\"<\n" +
	"\x0eRawTransaction\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\"P\n" +
	"\fSendResponse\x12\x1c\n" +
	"\terrorCode\x18\x01 \x01(\x05R\terrorCode\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage\"\v\n" +
	"\tChainSpec\"\a\n" +
	"\x05Empty\"\xa6\x05\n" +
	"\n" +
	"LightdInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\"\n" +
	"\ftaddrSupport\x18\x03 \x01(\bR\ftaddrSupport\x12\x1c\n" +
	"\tchainName\x18\x04 \x01(\tR\tchainName\x128\n" +
	"\x17saplingActivationHeight\x18\x05 \x01(\x04R\x17saplingActivationHeight\x12,\n" +
	"\x11consensusBranchId\x18\x06 \x01(\tR\x11consensusBranchId\x12 \n" +
	"\vblockHeight\x18\a \x01(\x04R\vblockHeight\x12\x1c\n" +
	"\tgitCommit\x18\b \x01(\tR\tgitCommit\x12\x16\n" +
	"\x06branch\x18\t \x01(\tR\x06branch\x12\x1c\n" +
	"\tbuildDate\x18\n" +
	" \x01(\tR\tbuildDate\x12\x1c\n" +
	"\tbuildUser\x18\v \x01(\tR\tbuildUser\x12(\n" +
	"\x0festimatedHeight\x18\f \x01(\x04R\x0festimatedHeight\x12 \n" +
	"\vzcashdBuild\x18\r \x01(\tR\vzcashdBuild\x12*\n" +
	"\x10zcashdSubversion\x18\x0e \x01(\tR\x10zcashdSubversion\x12(\n" +
	"\x0fdonationAddress\x18\x0f \x01(\tR\x0fdonationAddress\x12 \n" +
	"\vupgradeName\x18\x10 \x01(\tR\vupgradeName\x12$\n" +
	"\rupgradeHeight\x18\x11 \x01(\x04R\rupgradeHeight\x12>\n" +
	"\x1alightwalletProtocolVersion\x18\x12 \x01(\tR\x1alightwalletProtocolVersion\"r\n" +
	"\x1dTransparentAddressBlockFilter\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x127\n" +
	"\x05range\x18\x02 \x01(\v2!.cash.z.wallet.sdk.rpc.BlockRangeR\x05range\"*\n" +
	"\bDuration\x12\x1e\n" +
	"\n" +
	"intervalUs\x18\x01 \x01(\x03R\n" +
	"intervalUs\"8\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05entry\x18\x01 \x01(\x03R\x05entry\x12\x12\n" +
	"\x04exit\x18\x02 \x01(\x03R\x04exit\"#\n" +
	"\aAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"+\n" +
	"\vAddressList\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\"%\n" +
	"\aBalance\x12\x1a\n" +
	"\bvalueZat\x18\x01 \x01(\x03R\bvalueZat\"\x8e\x01\n" +
	"\x13GetMempoolTxRequest\x122\n" +
	"\x15exclude_txid_suffixes\x18\x01 \x03(\fR\x13excludeTxidSuffixes\x12=\n" +
	"\tpoolTypes\x18\x03 \x03(\x0e2\x1f.cash.z.wallet.sdk.rpc.PoolTypeR\tpoolTypesJ\x04\b\x02\x10\x03\"\xa9\x01\n" +
	"\tTreeState\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x12\n" +
	"\x04time\x18\x04 \x01(\rR\x04time\x12 \n" +
	"\vsaplingTree\x18\x05 \x01(\tR\vsaplingTree\x12 \n" +
	"\vorchardTree\x18\x06 \x01(\tR\vorchardTree\"\xa9\x01\n" +
	"\x12GetSubtreeRootsArg\x12\x1e\n" +
	"\n" +
	"startIndex\x18\x01 \x01(\rR\n" +
	"startIndex\x12S\n" +
	"\x10shieldedProtocol\x18\x02 \x01(\x0e2'.cash.z.wallet.sdk.rpc.ShieldedProtocolR\x10shieldedProtocol\x12\x1e\n" +
	"\n" +
	"maxEntries\x18\x03 \x01(\rR\n" +
	"maxEntries\"\x91\x01\n" +
	"\vSubtreeRoot\x12\x1a\n" +
	"\brootHash\x18\x02 \x01(\fR\brootHash\x120\n" +
	"\x13completingBlockHash\x18\x03 \x01(\fR\x13completingBlockHash\x124\n" +
	"\x15completingBlockHeight\x18\x04 \x01(\x04R\x15completingBlockHeight\"t\n" +
	"\x12GetAddressUtxosArg\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12 \n" +
	"\vstartHeight\x18\x02 \x01(\x04R\vstartHeight\x12\x1e\n" +
	"\n" +
	"maxEntries\x18\x03 \x01(\rR\n" +
	"maxEntries\"\xa6\x01\n" +
	"\x14GetAddressUtxosReply\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\fR\x04txid\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x16\n" +
	"\x06script\x18\x03 \x01(\fR\x06script\x12\x1a\n" +
	"\bvalueZat\x18\x04 \x01(\x03R\bvalueZat\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x04R\x06height\"k\n" +
	"\x18GetAddressUtxosReplyList\x12O\n" +
	"\faddressUtxos\x18\x01 \x03(\v2+.cash.z.wallet.sdk.rpc.GetAddressUtxosReplyR\faddressUtxos\"\x15\n" +
	"\x13GetPirParamsRequest\"\x96\x01\n" +
	"\fCuckooParams\x12\x1e\n" +
	"\n" +
	"numBuckets\x18\x01 \x01(\x04R\n" +
	"numBuckets\x12\x1e\n" +
	"\n" +
	"bucketSize\x18\x02 \x01(\rR\n" +
	"bucketSize\x12\x1a\n" +
	"\bhashSeed\x18\x03 \x01(\fR\bhashSeed\x12*\n" +
	"\x10numHashFunctions\x18\x04 \x01(\rR\x10numHashFunctions\"b\n" +
	"\n" +
	"YpirParams\x12\x18\n" +
	"\anumRows\x18\x01 \x01(\x04R\anumRows\x12\x18\n" +
	"\anumCols\x18\x02 \x01(\x04R\anumCols\x12 \n" +
	"\velementSize\x18\x03 \x01(\x04R\velementSize\"}\n" +
	"\rInspireParams\x12\x18\n" +
	"\anumRows\x18\x01 \x01(\x04R\anumRows\x12\x18\n" +
	"\anumCols\x18\x02 \x01(\x04R\anumCols\x12 \n" +
	"\velementSize\x18\x03 \x01(\x04R\velementSize\x12\x16\n" +
	"\x06factor\x18\x04 \x01(\rR\x06factor\"\xd7\x02\n" +
	"\x11PirParamsResponse\x12(\n" +
	"\x0fpirCutoffHeight\x18\x01 \x01(\x04R\x0fpirCutoffHeight\x12G\n" +
	"\fcuckooParams\x18\x02 \x01(\v2#.cash.z.wallet.sdk.rpc.CuckooParamsR\fcuckooParams\x12A\n" +
	"\n" +
	"ypirParams\x18\x03 \x01(\v2!.cash.z.wallet.sdk.rpc.YpirParamsR\n" +
	"ypirParams\x12J\n" +
	"\rinspireParams\x18\x04 \x01(\v2$.cash.z.wallet.sdk.rpc.InspireParamsR\rinspireParams\x12$\n" +
	"\rnumNullifiers\x18\x05 \x01(\x04R\rnumNullifiers\x12\x1a\n" +
	"\bpirReady\x18\x06 \x01(\bR\bpirReady\"(\n" +
	"\x10YpirQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\fR\x05query\"/\n" +
	"\x11YpirQueryResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\"+\n" +
	"\x13InspireQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\fR\x05query\"2\n" +
	"\x14InspireQueryResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\"\x15\n" +
	"\x13GetPirStatusRequest\"\xab\x02\n" +
	"\x11PirStatusResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12 \n" +
	"\vpirDbHeight\x18\x03 \x01(\x04R\vpirDbHeight\x12$\n" +
	"\rpendingBlocks\x18\x04 \x01(\rR\rpendingBlocks\x12$\n" +
	"\rnumNullifiers\x18\x05 \x01(\x04R\rnumNullifiers\x12\x1e\n" +
	"\n" +
	"numBuckets\x18\x06 \x01(\x04R\n" +
	"numBuckets\x12,\n" +
	"\x11rebuildInProgress\x18\a \x01(\bR\x11rebuildInProgress\x12$\n" +
	"\rlastBuildTime\x18\b \x01(\tR\rlastBuildTime*L\n" +
	"\bPoolType\x12\x15\n" +
	"\x11POOL_TYPE_INVALID\x10\x00\x12\x0f\n" +
	"\vTRANSPARENT\x10\x01\x12\v\n" +
	"\aSAPLING\x10\x02\x12\v\n" +
	"\aORCHARD\x10\x03*,\n" +
	"\x10ShieldedProtocol\x12\v\n" +
	"\asapling\x10\x00\x12\v\n" +
	"\aorchard\x10\x012\xbf\x12\n" +
	"\x11CompactTxStreamer\x12T\n" +
	"\x0eGetLatestBlock\x12 .cash.z.wallet.sdk.rpc.ChainSpec\x1a\x1e.cash.z.wallet.sdk.rpc.BlockID\"\x00\x12Q\n" +
	"\bGetBlock\x12\x1e.cash.z.wallet.sdk.rpc.BlockID\x1a#.cash.z.wallet.sdk.rpc.CompactBlock\"\x00\x12[\n" +
	"\x12GetBlockNullifiers\x12\x1e.cash.z.wallet.sdk.rpc.BlockID\x1a#.cash.z.wallet.sdk.rpc.CompactBlock\"\x00\x12[\n" +
	"\rGetBlockRange\x12!.cash.z.wallet.sdk.rpc.BlockRange\x1a#.cash.z.wallet.sdk.rpc.CompactBlock\"\x000\x01\x12e\n" +
	"\x17GetBlockRangeNullifiers\x12!.cash.z.wallet.sdk.rpc.BlockRange\x1a#.cash.z.wallet.sdk.rpc.CompactBlock\"\x000\x01\x12Z\n" +
	"\x0eGetTransaction\x12\x1f.cash.z.wallet.sdk.rpc.TxFilter\x1a%.cash.z.wallet.sdk.rpc.RawTransaction\"\x00\x12_\n" +
	"\x0fSendTransaction\x12%.cash.z.wallet.sdk.rpc.RawTransaction\x1a#.cash.z.wallet.sdk.rpc.SendResponse\"\x00\x12s\n" +
	"\x10GetTaddressTxids\x124.cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter\x1a%.cash.z.wallet.sdk.rpc.RawTransaction\"\x000\x01\x12z\n" +
	"\x17GetTaddressTransactions\x124.cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter\x1a%.cash.z.wallet.sdk.rpc.RawTransaction\"\x000\x01\x12Z\n" +
	"\x12GetTaddressBalance\x12\".cash.z.wallet.sdk.rpc.AddressList\x1a\x1e.cash.z.wallet.sdk.rpc.Balance\"\x00\x12^\n" +
	"\x18GetTaddressBalanceStream\x12\x1e.cash.z.wallet.sdk.rpc.Address\x1a\x1e.cash.z.wallet.sdk.rpc.Balance\"\x00(\x01\x12`\n" +
	"\fGetMempoolTx\x12*.cash.z.wallet.sdk.rpc.GetMempoolTxRequest\x1a .cash.z.wallet.sdk.rpc.CompactTx\"\x000\x01\x12[\n" +
	"\x10GetMempoolStream\x12\x1c.cash.z.wallet.sdk.rpc.Empty\x1a%.cash.z.wallet.sdk.rpc.RawTransaction\"\x000\x01\x12R\n" +
	"\fGetTreeState\x12\x1e.cash.z.wallet.sdk.rpc.BlockID\x1a .cash.z.wallet.sdk.rpc.TreeState\"\x00\x12V\n" +
	"\x12GetLatestTreeState\x12\x1c.cash.z.wallet.sdk.rpc.Empty\x1a .cash.z.wallet.sdk.rpc.TreeState\"\x00\x12d\n" +
	"\x0fGetSubtreeRoots\x12).cash.z.wallet.sdk.rpc.GetSubtreeRootsArg\x1a\".cash.z.wallet.sdk.rpc.SubtreeRoot\"\x000\x01\x12o\n" +
	"\x0fGetAddressUtxos\x12).cash.z.wallet.sdk.rpc.GetAddressUtxosArg\x1a/.cash.z.wallet.sdk.rpc.GetAddressUtxosReplyList\"\x00\x12s\n" +
	"\x15GetAddressUtxosStream\x12).cash.z.wallet.sdk.rpc.GetAddressUtxosArg\x1a+.cash.z.wallet.sdk.rpc.GetAddressUtxosReply\"\x000\x01\x12R\n" +
	"\rGetLightdInfo\x12\x1c.cash.z.wallet.sdk.rpc.Empty\x1a!.cash.z.wallet.sdk.rpc.LightdInfo\"\x00\x12N\n" +
	"\x04Ping\x12\x1f.cash.z.wallet.sdk.rpc.Duration\x1a#.cash.z.wallet.sdk.rpc.PingResponse\"\x00\x12f\n" +
	"\fGetPirParams\x12*.cash.z.wallet.sdk.rpc.GetPirParamsRequest\x1a(.cash.z.wallet.sdk.rpc.PirParamsResponse\"\x00\x12`\n" +
	"\tYpirQuery\x12'.cash.z.wallet.sdk.rpc.YpirQueryRequest\x1a(.cash.z.wallet.sdk.rpc.YpirQueryResponse\"\x00\x12i\n" +
	"\fInspireQuery\x12*.cash.z.wallet.sdk.rpc.InspireQueryRequest\x1a+.cash.z.wallet.sdk.rpc.InspireQueryResponse\"\x00\x12f\n" +
	"\fGetPirStatus\x12*.cash.z.wallet.sdk.rpc.GetPirStatusRequest\x1a(.cash.z.wallet.sdk.rpc.PirStatusResponse\"\x00B\x1bZ\x16lightwalletd/walletrpc\xba\x02\x00b\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_service_proto_goTypes = []any{
	(PoolType)(0),                         // 0: cash.z.wallet.sdk.rpc.PoolType
	(ShieldedProtocol)(0),                 // 1: cash.z.wallet.sdk.rpc.ShieldedProtocol
	(*BlockID)(nil),                       // 2: cash.z.wallet.sdk.rpc.BlockID
	(*BlockRange)(nil),                    // 3: cash.z.wallet.sdk.rpc.BlockRange
	(*TxFilter)(nil),                      // 4: cash.z.wallet.sdk.rpc.TxFilter
	(*RawTransaction)(nil),                // 5: cash.z.wallet.sdk.rpc.RawTransaction
	(*SendResponse)(nil),                  // 6: cash.z.wallet.sdk.rpc.SendResponse
	(*ChainSpec)(nil),                     // 7: cash.z.wallet.sdk.rpc.ChainSpec
	(*Empty)(nil),                         // 8: cash.z.wallet.sdk.rpc.Empty
	(*LightdInfo)(nil),                    // 9: cash.z.wallet.sdk.rpc.LightdInfo
	(*TransparentAddressBlockFilter)(nil), // 10: cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter
	(*Duration)(nil),                      // 11: cash.z.wallet.sdk.rpc.Duration
	(*PingResponse)(nil),                  // 12: cash.z.wallet.sdk.rpc.PingResponse
	(*Address)(nil),                       // 13: cash.z.wallet.sdk.rpc.Address
	(*AddressList)(nil),                   // 14: cash.z.wallet.sdk.rpc.AddressList
	(*Balance)(nil),                       // 15: cash.z.wallet.sdk.rpc.Balance
	(*GetMempoolTxRequest)(nil),           // 16: cash.z.wallet.sdk.rpc.GetMempoolTxRequest
	(*TreeState)(nil),                     // 17: cash.z.wallet.sdk.rpc.TreeState
	(*GetSubtreeRootsArg)(nil),            // 18: cash.z.wallet.sdk.rpc.GetSubtreeRootsArg
	(*SubtreeRoot)(nil),                   // 19: cash.z.wallet.sdk.rpc.SubtreeRoot
	(*GetAddressUtxosArg)(nil),            // 20: cash.z.wallet.sdk.rpc.GetAddressUtxosArg
	(*GetAddressUtxosReply)(nil),          // 21: cash.z.wallet.sdk.rpc.GetAddressUtxosReply
	(*GetAddressUtxosReplyList)(nil),      // 22: cash.z.wallet.sdk.rpc.GetAddressUtxosReplyList
	(*GetPirParamsRequest)(nil),           // 23: cash.z.wallet.sdk.rpc.GetPirParamsRequest
	(*CuckooParams)(nil),                  // 24: cash.z.wallet.sdk.rpc.CuckooParams
	(*YpirParams)(nil),                    // 25: cash.z.wallet.sdk.rpc.YpirParams
	(*InspireParams)(nil),                 // 26: cash.z.wallet.sdk.rpc.InspireParams
	(*PirParamsResponse)(nil),             // 27: cash.z.wallet.sdk.rpc.PirParamsResponse
	(*YpirQueryRequest)(nil),              // 28: cash.z.wallet.sdk.rpc.YpirQueryRequest
	(*YpirQueryResponse)(nil),             // 29: cash.z.wallet.sdk.rpc.YpirQueryResponse
	(*InspireQueryRequest)(nil),           // 30: cash.z.wallet.sdk.rpc.InspireQueryRequest
	(*InspireQueryResponse)(nil),          // 31: cash.z.wallet.sdk.rpc.InspireQueryResponse
	(*GetPirStatusRequest)(nil),           // 32: cash.z.wallet.sdk.rpc.GetPirStatusRequest
	(*PirStatusResponse)(nil),             // 33: cash.z.wallet.sdk.rpc.PirStatusResponse
	(*CompactBlock)(nil),                  // 34: cash.z.wallet.sdk.rpc.CompactBlock
	(*CompactTx)(nil),                     // 35: cash.z.wallet.sdk.rpc.CompactTx
}
var file_service_proto_depIdxs = []int32{
	2,  // 0: cash.z.wallet.sdk.rpc.BlockRange.start:type_name -> cash.z.wallet.sdk.rpc.BlockID
	2,  // 1: cash.z.wallet.sdk.rpc.BlockRange.end:type_name -> cash.z.wallet.sdk.rpc.BlockID
	0,  // 2: cash.z.wallet.sdk.rpc.BlockRange.poolTypes:type_name -> cash.z.wallet.sdk.rpc.PoolType
	2,  // 3: cash.z.wallet.sdk.rpc.TxFilter.block:type_name -> cash.z.wallet.sdk.rpc.BlockID
	3,  // 4: cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter.range:type_name -> cash.z.wallet.sdk.rpc.BlockRange
	0,  // 5: cash.z.wallet.sdk.rpc.GetMempoolTxRequest.poolTypes:type_name -> cash.z.wallet.sdk.rpc.PoolType
	1,  // 6: cash.z.wallet.sdk.rpc.GetSubtreeRootsArg.shieldedProtocol:type_name -> cash.z.wallet.sdk.rpc.ShieldedProtocol
	21, // 7: cash.z.wallet.sdk.rpc.GetAddressUtxosReplyList.addressUtxos:type_name -> cash.z.wallet.sdk.rpc.GetAddressUtxosReply
	24, // 8: cash.z.wallet.sdk.rpc.PirParamsResponse.cuckooParams:type_name -> cash.z.wallet.sdk.rpc.CuckooParams
	25, // 9: cash.z.wallet.sdk.rpc.PirParamsResponse.ypirParams:type_name -> cash.z.wallet.sdk.rpc.YpirParams
	26, // 10: cash.z.wallet.sdk.rpc.PirParamsResponse.inspireParams:type_name -> cash.z.wallet.sdk.rpc.InspireParams
	7,  // 11: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLatestBlock:input_type -> cash.z.wallet.sdk.rpc.ChainSpec
	2,  // 12: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlock:input_type -> cash.z.wallet.sdk.rpc.BlockID
	2,  // 13: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockNullifiers:input_type -> cash.z.wallet.sdk.rpc.BlockID
	3,  // 14: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockRange:input_type -> cash.z.wallet.sdk.rpc.BlockRange
	3,  // 15: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockRangeNullifiers:input_type -> cash.z.wallet.sdk.rpc.BlockRange
	4,  // 16: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTransaction:input_type -> cash.z.wallet.sdk.rpc.TxFilter
	5,  // 17: cash.z.wallet.sdk.rpc.CompactTxStreamer.SendTransaction:input_type -> cash.z.wallet.sdk.rpc.RawTransaction
	10, // 18: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressTxids:input_type -> cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter
	10, // 19: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressTransactions:input_type -> cash.z.wallet.sdk.rpc.TransparentAddressBlockFilter
	14, // 20: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressBalance:input_type -> cash.z.wallet.sdk.rpc.AddressList
	13, // 21: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressBalanceStream:input_type -> cash.z.wallet.sdk.rpc.Address
	16, // 22: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetMempoolTx:input_type -> cash.z.wallet.sdk.rpc.GetMempoolTxRequest
	8,  // 23: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetMempoolStream:input_type -> cash.z.wallet.sdk.rpc.Empty
	2,  // 24: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTreeState:input_type -> cash.z.wallet.sdk.rpc.BlockID
	8,  // 25: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLatestTreeState:input_type -> cash.z.wallet.sdk.rpc.Empty
	18, // 26: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetSubtreeRoots:input_type -> cash.z.wallet.sdk.rpc.GetSubtreeRootsArg
	20, // 27: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetAddressUtxos:input_type -> cash.z.wallet.sdk.rpc.GetAddressUtxosArg
	20, // 28: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetAddressUtxosStream:input_type -> cash.z.wallet.sdk.rpc.GetAddressUtxosArg
	8,  // 29: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLightdInfo:input_type -> cash.z.wallet.sdk.rpc.Empty
	11, // 30: cash.z.wallet.sdk.rpc.CompactTxStreamer.Ping:input_type -> cash.z.wallet.sdk.rpc.Duration
	23, // 31: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetPirParams:input_type -> cash.z.wallet.sdk.rpc.GetPirParamsRequest
	28, // 32: cash.z.wallet.sdk.rpc.CompactTxStreamer.YpirQuery:input_type -> cash.z.wallet.sdk.rpc.YpirQueryRequest
	30, // 33: cash.z.wallet.sdk.rpc.CompactTxStreamer.InspireQuery:input_type -> cash.z.wallet.sdk.rpc.InspireQueryRequest
	32, // 34: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetPirStatus:input_type -> cash.z.wallet.sdk.rpc.GetPirStatusRequest
	2,  // 35: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLatestBlock:output_type -> cash.z.wallet.sdk.rpc.BlockID
	34, // 36: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlock:output_type -> cash.z.wallet.sdk.rpc.CompactBlock
	34, // 37: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockNullifiers:output_type -> cash.z.wallet.sdk.rpc.CompactBlock
	34, // 38: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockRange:output_type -> cash.z.wallet.sdk.rpc.CompactBlock
	34, // 39: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetBlockRangeNullifiers:output_type -> cash.z.wallet.sdk.rpc.CompactBlock
	5,  // 40: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTransaction:output_type -> cash.z.wallet.sdk.rpc.RawTransaction
	6,  // 41: cash.z.wallet.sdk.rpc.CompactTxStreamer.SendTransaction:output_type -> cash.z.wallet.sdk.rpc.SendResponse
	5,  // 42: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressTxids:output_type -> cash.z.wallet.sdk.rpc.RawTransaction
	5,  // 43: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressTransactions:output_type -> cash.z.wallet.sdk.rpc.RawTransaction
	15, // 44: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressBalance:output_type -> cash.z.wallet.sdk.rpc.Balance
	15, // 45: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTaddressBalanceStream:output_type -> cash.z.wallet.sdk.rpc.Balance
	35, // 46: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetMempoolTx:output_type -> cash.z.wallet.sdk.rpc.CompactTx
	5,  // 47: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetMempoolStream:output_type -> cash.z.wallet.sdk.rpc.RawTransaction
	17, // 48: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetTreeState:output_type -> cash.z.wallet.sdk.rpc.TreeState
	17, // 49: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLatestTreeState:output_type -> cash.z.wallet.sdk.rpc.TreeState
	19, // 50: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetSubtreeRoots:output_type -> cash.z.wallet.sdk.rpc.SubtreeRoot
	22, // 51: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetAddressUtxos:output_type -> cash.z.wallet.sdk.rpc.GetAddressUtxosReplyList
	21, // 52: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetAddressUtxosStream:output_type -> cash.z.wallet.sdk.rpc.GetAddressUtxosReply
	9,  // 53: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetLightdInfo:output_type -> cash.z.wallet.sdk.rpc.LightdInfo
	12, // 54: cash.z.wallet.sdk.rpc.CompactTxStreamer.Ping:output_type -> cash.z.wallet.sdk.rpc.PingResponse
	27, // 55: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetPirParams:output_type -> cash.z.wallet.sdk.rpc.PirParamsResponse
	29, // 56: cash.z.wallet.sdk.rpc.CompactTxStreamer.YpirQuery:output_type -> cash.z.wallet.sdk.rpc.YpirQueryResponse
	31, // 57: cash.z.wallet.sdk.rpc.CompactTxStreamer.InspireQuery:output_type -> cash.z.wallet.sdk.rpc.InspireQueryResponse
	33, // 58: cash.z.wallet.sdk.rpc.CompactTxStreamer.GetPirStatus:output_type -> cash.z.wallet.sdk.rpc.PirStatusResponse
	35, // [35:59] is the sub-list for method output_type
	11, // [11:35] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_compact_formats_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
